/**
 * COP (Common Operating Picture) Type Definitions
 *
 * Shared type contracts for the COP layer system. These interfaces
 * define the full data model for layers, symbols, specs, lifecycle
 * states, snapshots, and review feedback.
 */

// ---------------------------------------------------------------------------
// Enums & Literal Unions
// ---------------------------------------------------------------------------

/** 4-state layer lifecycle: Draft -> Review -> Published -> COP */
export type LayerState = 'draft' | 'review' | 'published' | 'cop';

/** COP layer types aligned to warfighting functions */
export type COPLayerType =
  | 'force_disposition'
  | 'objectives'
  | 'control_measures'
  | 'intel'
  | 'logistics'
  | 'c2';

/** MIL-STD-2525D standard identity affiliation */
export type Affiliation = 'friendly' | 'enemy' | 'neutral' | 'unknown';

/** COP viewing perspective toggle */
export type Perspective = 'friendly' | 'adversary' | 'combined';

// ---------------------------------------------------------------------------
// Symbol & Control Measure Specs
// ---------------------------------------------------------------------------

/** Position as latitude/longitude */
export interface LatLng {
  lat: number;
  lng: number;
}

/**
 * Declarative spec for a single military symbol on the COP.
 * Standard symbols are rendered via milsymbol from this spec;
 * the LLM never generates SVG for standard symbols.
 */
export interface COPSymbolSpec {
  entityId: string;
  /** MIL-STD-2525D 20-character SIDC code */
  sidc: string;
  position: LatLng;
  designation: string;
  affiliation: Affiliation;
  /** Movement path across temporal phases */
  movementPath?: Array<{ phase: number; position: LatLng }>;
  /** RAFT entity IDs for hover/click detail */
  linkedEntities: string[];
  /** CCO class URI for ontology validation */
  ccoClass: string;
  /** Agent confidence in placement (0-1) */
  confidence: number;
  /** Source authority for conflict resolution ranking */
  sourceAuthority: string;
}

/**
 * Control measure overlay (boundaries, phase lines, axes of advance, etc.)
 */
export interface COPControlMeasureSpec {
  id: string;
  type:
    | 'boundary'
    | 'phase_line'
    | 'objective_area'
    | 'axis_of_advance'
    | 'route';
  points: LatLng[];
  label: string;
  style?: Record<string, string>;
  /** Phase range this measure is visible during */
  phaseRange?: { start: number; end: number };
}

/**
 * Custom annotation (LLM-generated SVG fragment).
 * All svgFragment content MUST be sanitized before storage and rendering.
 */
export interface COPAnnotationSpec {
  id: string;
  /** Sanitized SVG fragment */
  svgFragment: string;
  position: LatLng;
  bounds?: { topLeft: LatLng; bottomRight: LatLng };
  /** Agent ID that generated this annotation */
  generatedBy: string;
  description: string;
}

/**
 * Temporal phase definition for phase slider / animated playback
 */
export interface COPPhaseSpec {
  phaseNumber: number;
  label: string;
  startTime?: string;
  endTime?: string;
  description?: string;
}

// ---------------------------------------------------------------------------
// Layer Spec (the core declarative JSON spec)
// ---------------------------------------------------------------------------

/**
 * Full declarative layer specification. This is the primary data structure
 * generated by COP sub-agents and assembled by the coordinator.
 */
export interface COPLayerSpec {
  layerId: string;
  layerType: COPLayerType;
  workspaceId: string; // Backend wire format — will be renamed when backend COP is updated
  sectionId: string;
  symbols: COPSymbolSpec[];
  controlMeasures: COPControlMeasureSpec[];
  customAnnotations: COPAnnotationSpec[];
  temporalPhases: COPPhaseSpec[];
  metadata: {
    generatedBy: string;
    generatedAt: string;
    sourceDocumentIds: string[];
    ccoValidated: boolean;
  };
}

// ---------------------------------------------------------------------------
// Review & Audit
// ---------------------------------------------------------------------------

/**
 * Staff review feedback on a layer.
 * Supports both spatial annotations (on specific entities/areas) and
 * general free-text comments.
 */
export interface ReviewFeedback {
  id: string;
  layerId: string;
  type: 'spatial_annotation' | 'general_comment';
  content: string;
  /** Position for spatial annotations */
  position?: LatLng;
  /** Entity reference for entity-specific feedback */
  entityId?: string;
  createdBy: string;
  createdAt: string;
}

/**
 * Audit trail entry for layer lifecycle transitions.
 * Supports recall accountability requirement.
 */
export interface AuditEntry {
  id: string;
  action: string;
  performedBy: string;
  performedAt: string;
  reason?: string;
  details?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Layer Entity
// ---------------------------------------------------------------------------

/**
 * Full COP layer entity with lifecycle state, version tracking,
 * review feedback, promotion/recall tracking, and audit trail.
 */
export interface COPLayer {
  id: string;
  workspaceId: string; // Backend wire format — will be renamed when backend COP is updated
  sectionId: string;
  layerType: COPLayerType;
  state: LayerState;
  currentVersion: number;
  spec: COPLayerSpec;
  reviewFeedback?: ReviewFeedback[];
  promotedBy?: string;
  promotedAt?: string;
  recalledBy?: string;
  recalledAt?: string;
  recallReason?: string;
  auditTrail: AuditEntry[];
  createdAt: string;
  updatedAt: string;
}

/**
 * Version snapshot created at each layer state transition.
 * Full snapshots at COP promotion; diffs for intermediate transitions.
 */
export interface LayerSnapshot {
  id: string;
  layerId: string;
  version: number;
  state: LayerState;
  spec: COPLayerSpec;
  transitionedBy: string;
  transitionedAt: string;
  previousState: LayerState;
}

// ---------------------------------------------------------------------------
// Conflict Detection
// ---------------------------------------------------------------------------

/**
 * Cross-section entity conflict detected when promoted layers
 * have overlapping or contradictory entities.
 */
export interface COPConflict {
  id: string;
  layerIdA: string;
  layerIdB: string;
  entityIdA: string;
  entityIdB: string;
  conflictType: 'position' | 'affiliation' | 'designation';
  description: string;
  resolved: boolean;
  resolvedBy?: string;
}

// ---------------------------------------------------------------------------
// UI Props
// ---------------------------------------------------------------------------

/**
 * Props for the COP layer controls panel.
 * Extends the IPBLayerControls pattern with opacity sliders
 * and perspective toggle.
 */
export interface COPLayerControlsProps {
  layers: COPLayer[];
  layerVisibility: Record<string, boolean>;
  layerOpacity: Record<string, number>;
  onVisibilityChange: (layerId: string, visible: boolean) => void;
  onOpacityChange: (layerId: string, opacity: number) => void;
  currentPerspective: Perspective;
  onPerspectiveChange: (perspective: Perspective) => void;
}
