/**
 * Ironclaw Action Registry
 *
 * Phase 30 Plan 03: Registers action types with risk levels, provides risk
 * classification lookup, and enforces per-user per-risk-level rate limiting
 * via an in-memory sliding window.
 *
 * Unknown action types default to 'high' risk (safe default per the
 * "always confirm by default" design decision).
 */

import {
  ActionRiskLevel,
  ACTION_RISK,
  RATE_LIMITS,
} from './ironclaw-types.js';

// ---------------------------------------------------------------------------
// Rate Limit Check Result
// ---------------------------------------------------------------------------

export interface RateLimitResult {
  allowed: boolean;
  retryAfter?: number;
}

// ---------------------------------------------------------------------------
// ActionRegistry
// ---------------------------------------------------------------------------

/**
 * Canonical action descriptions generated by the backend.
 * These are shown on action cards instead of agent-supplied text
 * to prevent social engineering via misleading descriptions.
 */
const CANONICAL_DESCRIPTIONS: Record<string, string> = {
  'bastion.problem_set.read': 'Read problem set details and configuration',
  'bastion.problem_set.list_children': 'List child problem sets',
  'bastion.problem_set.update_field': 'Update a field on a problem set',
  'bastion.problem_set.create_child': 'Create a new child problem set',
  'bastion.problem_set.configure_agents': 'Configure AI agents for a problem set (HIGH RISK)',
  'bastion.resource.create': 'Create a resource in the registry',
  'bastion.resource.delete': 'Delete a resource from the registry (HIGH RISK)',
  'bastion.gate.create': 'Create a decision gate for approval workflow',
  'bastion.code.create_pr': 'Create a GitHub PR with code changes (HIGH RISK)',
  'bastion.system.update_config': 'Update system-level configuration (HIGH RISK)',
  // Agent/team delegation
  'agent.list_active': 'List all currently active agents',
  'agent.get_status': 'Get health and status summary for a specific agent',
  'agent.assign_to_problem_set': 'Assign an agent to a problem set',
  'agent.unassign_from_problem_set': 'Unassign an agent from a problem set',
  'agent.form_team_for_task': 'Activate a team to work on a specific task',
  // Agent/tool/team CRUD
  'agent.create': 'Create a new AI agent with specified capabilities and clearance',
  'agent.update': 'Update an existing agent\'s configuration',
  'agent.delete': 'Permanently delete an agent and all its data (HIGH RISK)',
  'agent.activate': 'Activate an agent (requires passing health gate)',
  'agent.deactivate': 'Deactivate an agent — stops it from being invoked',
  'tool.create': 'Register a new MCP tool in the tool registry',
  'tool.update': 'Update an existing tool\'s configuration',
  'tool.delete': 'Remove a tool from the registry (HIGH RISK)',
  'tool.assign_to_agent': 'Assign a tool to an agent for use during execution',
  'team.create': 'Create a new agent team with workflow configuration',
  'team.update': 'Update an existing team\'s members or workflow',
  'team.delete': 'Permanently delete a team (HIGH RISK)',
  'team.add_member': 'Add an agent to an existing team',
  'team.remove_member': 'Remove an agent from a team',
  // Skill CRUD
  'skill.create': 'Create a new agent skill definition',
  'skill.update': 'Update an existing skill definition',
  'skill.delete': 'Permanently delete a skill — affects all agents using it (HIGH RISK)',
  'skill.assign': 'Assign a skill to an agent',
  'skill.unassign': 'Remove a skill from an agent',
  // Field write-back
  'field.write': 'Apply a suggested value to a problem set field',
  'field.write_sensitive': 'Update a sensitive field (e.g., mission statement, ROE) — requires explicit approval',
  // Knowledge graph (read-only)
  'bastion.graph.search_actors': 'Search the knowledge graph for actors by name or type',
  'bastion.graph.get_actor': 'Get full details of a specific actor node with relationships',
  'bastion.graph.query': 'Run a read-only Cypher query against the knowledge graph',
  'bastion.graph.stats': 'Get knowledge graph statistics (node counts, top actors)',
};

export class ActionRegistry {
  /** Registered action types mapped to their risk level. */
  private readonly actions = new Map<string, ActionRiskLevel>();

  /** Sliding-window timestamps: key = `${userDid}:${riskBucket}`, value = timestamps (ms). */
  private readonly rateLimitMap = new Map<string, number[]>();

  /**
   * When true, the registry is frozen — no new registrations or risk level
   * changes are permitted. Set after startup tool registration completes to
   * prevent the agent from downgrading its own risk classifications at runtime.
   */
  private locked = false;

  constructor() {
    // Pre-populate from the canonical ACTION_RISK map in ironclaw-types.
    for (const [type, risk] of Object.entries(ACTION_RISK)) {
      this.actions.set(type, risk);
    }
  }

  // =========================================================================
  // Registry Lock
  // =========================================================================

  /**
   * Freeze the registry. Call once after startup tool registration is complete.
   * After this, registerAction() rejects all changes.
   */
  lock(): void {
    this.locked = true;
    console.log(
      `[action-registry] Registry locked with ${this.actions.size} action types. No further modifications permitted.`,
    );
  }

  /** Whether the registry is currently locked. */
  isLocked(): boolean {
    return this.locked;
  }

  // =========================================================================
  // Action Type Registration
  // =========================================================================

  /**
   * Return the risk level for a given action type.
   * Unknown types default to 'high' (safe default).
   */
  getRiskLevel(actionType: string): ActionRiskLevel {
    return this.actions.get(actionType) ?? ActionRiskLevel.high;
  }

  /** Whether the action type has been explicitly registered. */
  isRegistered(actionType: string): boolean {
    return this.actions.has(actionType);
  }

  /**
   * Register an action type's risk level.
   *
   * Guardrails:
   * - Rejected entirely after lock() (post-startup).
   * - Risk can never be downgraded, only elevated (even before lock).
   */
  registerAction(actionType: string, riskLevel: ActionRiskLevel): void {
    if (this.locked) {
      console.warn(
        `[action-registry] REJECTED: Attempt to modify locked registry (action=${actionType}, risk=${riskLevel})`,
      );
      return;
    }

    const existing = this.actions.get(actionType);
    if (existing) {
      const riskOrder: Record<string, number> = { low: 0, medium: 1, high: 2 };
      if (riskOrder[riskLevel] < riskOrder[existing]) {
        console.warn(
          `[action-registry] REJECTED: Risk downgrade attempt for "${actionType}" (${existing} -> ${riskLevel})`,
        );
        return;
      }
    }

    this.actions.set(actionType, riskLevel);
  }

  /**
   * Get the canonical backend-generated description for an action type.
   * Falls back to a generic description if the action type is unknown.
   * Prevents social engineering via agent-supplied misleading descriptions.
   */
  getDescription(actionType: string): string {
    return CANONICAL_DESCRIPTIONS[actionType] ?? `Action: ${actionType}`;
  }

  /** List all registered actions with their risk levels. */
  getAllActions(): Array<{ type: string; riskLevel: ActionRiskLevel }> {
    return Array.from(this.actions.entries()).map(([type, riskLevel]) => ({
      type,
      riskLevel,
    }));
  }

  // =========================================================================
  // Rate Limiting (in-memory sliding window)
  // =========================================================================

  /**
   * Check whether a user is within the rate limit for the given action type.
   *
   * Rate limit buckets:
   *  - Actions starting with 'code.' use the dedicated `code_pr` window (5/hour).
   *  - All other actions use their risk level window (low 60/min, medium 10/min, high 3/min).
   */
  checkRateLimit(userDid: string, actionType: string): RateLimitResult {
    const isCodeAction = actionType.startsWith('code.');
    const riskLevel = this.getRiskLevel(actionType);
    const bucket = isCodeAction ? 'code_pr' : riskLevel;
    const config = RATE_LIMITS[bucket];

    const key = `${userDid}:${bucket}`;
    const now = Date.now();
    const windowMs = config.window_seconds * 1000;
    const cutoff = now - windowMs;

    // Get and clean up old entries
    const timestamps = this.rateLimitMap.get(key) ?? [];
    const active = timestamps.filter((ts) => ts > cutoff);

    if (active.length >= config.max) {
      // Find when the earliest active entry will expire
      const earliest = active[0]!;
      const retryAfter = Math.ceil((earliest + windowMs - now) / 1000);
      this.rateLimitMap.set(key, active);
      return { allowed: false, retryAfter };
    }

    // Record this check as a new entry (caller records when action proceeds)
    active.push(now);
    this.rateLimitMap.set(key, active);
    return { allowed: true };
  }
}

// ---------------------------------------------------------------------------
// Singleton
// ---------------------------------------------------------------------------

export const actionRegistry = new ActionRegistry();
