/**
 * Ironclaw Orchestration Service
 *
 * Phase 30 Plan 02: Bridges frontend users to the Ironclaw sidecar.
 * Manages session lifecycle, SSE stream parsing, message persistence,
 * specialist delegation attribution, and WebSocket forwarding.
 */

import { ironclawClient, parseSSEStream } from './ironclaw-client.js';
import { ironclawStore } from './ironclaw-store.js';
import { toolBridge } from './tool-bridge.js';
import { actionRegistry } from './action-registry.js';
import { getMessageBus } from '../messaging/message-bus.js';
import type {
  IronclawChatMessage,
  ActionCardData,
} from './ironclaw-types.js';

const SERVICE_DID = 'did:system:ironclaw-service';

// ---------------------------------------------------------------------------
// WebSocket channel helper
// ---------------------------------------------------------------------------

/** Strict pattern for channel names — prevents path traversal and injection. */
const CHANNEL_NAME_PATTERN = /^[a-zA-Z0-9_-]+$/;

function wsChannel(problemSetId: string): string {
  if (!CHANNEL_NAME_PATTERN.test(problemSetId)) {
    throw new Error(
      `[ironclaw] Invalid problemSetId for channel name: "${problemSetId}". ` +
      'Must match [a-zA-Z0-9_-]+.',
    );
  }
  return `ironclaw.${problemSetId}`;
}

async function publishToChannel(
  problemSetId: string,
  messageType: string,
  payload: unknown,
): Promise<void> {
  try {
    const bus = getMessageBus();
    await bus.publish({
      sourceDid: SERVICE_DID,
      sourceType: 'system',
      destinationType: 'channel',
      destinationTarget: wsChannel(problemSetId),
      messageType,
      payload,
    });
  } catch (err) {
    // Non-blocking: log but don't fail the message flow
    console.error(`[ironclaw] WebSocket publish error (${messageType}):`, err);
  }
}

// ---------------------------------------------------------------------------
// IronclawService
// ---------------------------------------------------------------------------

export class IronclawService {
  /**
   * Handle an incoming user message:
   * 1. Get or create session
   * 2. Initialize Ironclaw session if needed
   * 3. Persist user message
   * 4. Stream response from Ironclaw sidecar
   * 5. Parse SSE events, detect specialist delegation
   * 6. Persist and forward each chunk via WebSocket
   */
  async handleMessage(
    problemSetId: string,
    userDid: string,
    content: string,
    mentionedAgent?: string,
  ): Promise<void> {
    // 1. Get or create local session
    const session = await ironclawStore.getOrCreateSession(problemSetId, userDid);

    // 2. If no Ironclaw-side session, create one with system prompt
    if (!session.ironclaw_session_id) {
      const systemPrompt = this.buildSystemPrompt(problemSetId);
      const result = await ironclawClient.createSession(
        session.id,
        systemPrompt,
      );
      // Update session with Ironclaw's session ID
      // (Store the mapping so subsequent messages use the same session)
      session.ironclaw_session_id = result.session_id;
    }

    // 3. Persist user message
    const userMsg = await ironclawStore.addMessage({
      problem_set_id: problemSetId,
      content,
      sender: 'user',
      specialist_id: null,
      specialist_display_name: null,
      delegated_by: null,
      action_card: null,
      step_progress: null,
    });

    // Publish user message to WebSocket
    await publishToChannel(problemSetId, 'ironclaw.user-message', userMsg);

    // 4. Send to Ironclaw sidecar and get SSE stream
    const stream = await ironclawClient.sendMessage(
      session.ironclaw_session_id!,
      content,
      mentionedAgent,
    );

    // 5-8. Parse SSE stream and process events
    for await (const event of parseSSEStream(stream)) {
      await this.processSSEEvent(problemSetId, event);
    }
  }

  /**
   * Process a single SSE event from the Ironclaw sidecar.
   * Detects specialist delegation, action cards, and regular messages.
   */
  private async processSSEEvent(
    problemSetId: string,
    event: { event?: string; data: string },
  ): Promise<void> {
    let parsed: Record<string, unknown>;
    try {
      parsed = JSON.parse(event.data) as Record<string, unknown>;
    } catch {
      // Non-JSON data (e.g. keepalive), skip
      return;
    }

    // Determine sender and specialist attribution
    const specialistId = (parsed.specialist_id as string) ?? null;
    const specialistDisplayName =
      (parsed.specialist_display_name as string) ?? null;
    const sender: IronclawChatMessage['sender'] = specialistId
      ? 'specialist'
      : 'ironclaw';
    const delegatedBy = specialistId ? 'ironclaw' : null;

    // Detect action card (tool_call event)
    // Security: description and risk_level are generated by the backend from
    // the action registry, NOT from agent-supplied text, to prevent social
    // engineering via misleading action descriptions.
    let actionCard: ActionCardData | null = null;
    if (parsed.tool_call || event.event === 'tool_call') {
      const toolCall = (parsed.tool_call ?? parsed) as Record<string, unknown>;
      const actionType = (toolCall.action_type as string) ?? '';
      actionCard = {
        action_id: (toolCall.action_id as string) ?? '',
        action_type: actionType,
        description: actionRegistry.getDescription(actionType),
        risk_level: actionRegistry.getRiskLevel(actionType),
        options: (toolCall.options as ActionCardData['options']) ?? ['yes', 'no'],
      };
    }

    const messageContent = (parsed.content as string) ?? (parsed.text as string) ?? '';
    if (!messageContent && !actionCard) return;

    // 6. Persist the message
    const chatMsg = await ironclawStore.addMessage({
      problem_set_id: problemSetId,
      content: messageContent,
      sender,
      specialist_id: specialistId,
      specialist_display_name: specialistDisplayName,
      delegated_by: delegatedBy,
      action_card: actionCard,
      step_progress: null,
    });

    // 7. Publish to WebSocket for real-time frontend updates
    await publishToChannel(problemSetId, 'ironclaw.response', chatMsg);
  }

  /**
   * Get chat history for a problem set.
   */
  async getHistory(
    problemSetId: string,
    limit?: number,
  ): Promise<IronclawChatMessage[]> {
    return ironclawStore.getHistory(problemSetId, limit);
  }

  /**
   * Check if the Ironclaw sidecar is healthy.
   */
  async isHealthy(): Promise<boolean> {
    return ironclawClient.healthCheck();
  }

  /**
   * Initialize BASTION MCP tools with the Ironclaw sidecar.
   * Should be called after Ironclaw is confirmed healthy.
   */
  async initializeTools(): Promise<void> {
    await toolBridge.registerTools();
  }

  /**
   * Startup initialization: wait for Ironclaw sidecar health, then register tools.
   * Retries up to 3 times with 5-second delays since Ironclaw container may
   * start slower than the backend.
   */
  async startupInit(): Promise<void> {
    const MAX_RETRIES = 3;
    const RETRY_DELAY_MS = 5000;

    for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
      try {
        const healthy = await this.isHealthy();
        if (healthy) {
          await this.initializeTools();
          console.log('[ironclaw-service] Startup init complete: tools registered');
          return;
        }
        console.warn(
          `[ironclaw-service] Health check failed (attempt ${attempt}/${MAX_RETRIES})`,
        );
      } catch (err) {
        console.warn(
          `[ironclaw-service] Startup init error (attempt ${attempt}/${MAX_RETRIES}):`,
          err instanceof Error ? err.message : err,
        );
      }

      if (attempt < MAX_RETRIES) {
        await new Promise((resolve) => setTimeout(resolve, RETRY_DELAY_MS));
      }
    }

    console.warn(
      '[ironclaw-service] Startup init failed after retries. Tools not registered. ' +
        'They can be registered later when Ironclaw becomes available.',
    );
  }

  /**
   * Build the system prompt for an Ironclaw session.
   * Establishes Ironclaw as the Chief of Staff with delegation rules.
   */
  buildSystemPrompt(problemSetId: string): string {
    return [
      'You are the Chief of Staff for this problem set.',
      `Problem Set ID: ${problemSetId}.`,
      'When a query is domain-specific, delegate to the appropriate specialist agent and attribute their response.',
      'Always confirm actions before executing.',
      'For ambiguous scope (this PS vs children), ask to clarify.',
      'Never assume.',
      '',
      '## Governance Constraints (non-negotiable)',
      'You are subject to the following constraints enforced at multiple layers.',
      'Do NOT attempt to circumvent, test, or probe these boundaries:',
      '- You CANNOT modify your own risk levels, rate limits, trust settings, or autonomy configuration.',
      '- You CANNOT modify gate enforcement, auto-approve, or bypass rules.',
      '- You CANNOT reconfigure your own agent settings or permissions.',
      '- You CANNOT create PRs that modify governance code, auth, gates, CI/CD, Docker, or build config files.',
      '- High-risk actions ALWAYS require a Decision Gate regardless of trust preferences.',
      '- All actions are logged with immutable audit trail anchored to blockchain.',
      '- Emergency mode requires system_admin role verified by zero-trust middleware.',
      '',
      'Specialist agents available:',
      '- J2 Intelligence: threat analysis, IPB, intelligence estimates',
      '- J3 Operations: COA development, scheme of maneuver, fires integration',
      '- J4 Logistics: sustainment, force projection, resource allocation',
      '- J5 Plans: strategic planning, campaign design, phase transitions',
      '- J6 Communications: C4ISR, network architecture, signal support',
      '',
      'When delegating, include the specialist_id and specialist_display_name in your response.',
      'When proposing actions that modify data, include a tool_call with action_id, action_type, description, risk_level, and options.',
    ].join('\n');
  }
}

// ---------------------------------------------------------------------------
// Singleton
// ---------------------------------------------------------------------------

export const ironclawService = new IronclawService();
