/**
 * MDMP Activity Registry
 *
 * Complete catalog of MDMP activities mapped through the Bastion governance
 * data model. Each activity is a populated MDMPActivity instance from mdmp-types.ts.
 *
 * Organization: By MDMP Phase (0-VIII)
 * Naming Convention: MDMP-{phase}-{sequence} (e.g., MDMP-0-01)
 *
 * Authority Distribution Summary:
 *   AI_AUTONOMOUS:    ~12% (22 activities) - Data pipelines, validation, monitoring
 *   AI_PRIMARY:       ~15% (28 activities) - Pattern recognition, sustainment modeling
 *   HYBRID_AI_LED:    ~33% (62 activities) - Analysis, COA gen, wargaming, orders
 *   HYBRID_HUMAN_LED: ~25% (47 activities) - Problem framing, risk analysis, intent
 *   HUMAN_ONLY:       ~15% (28 activities) - Authority, ethics, risk acceptance
 *
 * References: mdmp-types.ts, mdmp-contracts.rs
 */

import {
  MDMPPhase, ActivityCategory, AuthorityDesignation, ControlPosture,
  DAOTier, AgentRole, AgentOutputType, GateType, PlanningProduct,
  VerificationMechanism, EvidenceType, RetentionPeriod, AuditRequirement,
  ChallengeType, ResponseDepth, CoalitionImpact, SharingLevel,
  ImplementationStatus, EscalationPath,
  type MDMPActivity,
} from './mdmp-types.js';

// ═══════════════════════════════════════════════════════════════════════════
// PHASE 0: CONTINUOUS ACTIVITIES
// Running infrastructure that feeds all subsequent phases.
// Highest concentration of AI_AUTONOMOUS activities.
// ═══════════════════════════════════════════════════════════════════════════

export const PHASE_0_ACTIVITIES: MDMPActivity[] = [
  // ── AI Autonomous: Data Pipelines ──
  {
    id: 'MDMP-0-01',
    mdmpPhase: MDMPPhase.PHASE_0_CONTINUOUS,
    category: ActivityCategory.DATA_AGGREGATION,
    description: 'Aggregate multi-source intelligence feeds into unified data lake (SIGINT, HUMINT, OSINT, GEOINT, MASINT)',
    authorityDesignation: AuthorityDesignation.AI_AUTONOMOUS,
    controlPosture: ControlPosture.FULLY_DELEGATED,
    daoTier: DAOTier.TACTICAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.STRATEGIC_FUSION, AgentRole.OSINT_MONITOR],
      agentOutputType: AgentOutputType.VALIDATION_RESULT,
      humanCheckpoint: { required: false, trigger: 'never', requiredRole: null, timeoutMs: null },
      confidenceThreshold: 0,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.AUTOMATED_VALIDATION,
      blockchainRecord: true,
      teeRequired: false,
      evidenceTypes: [EvidenceType.VALIDATION_LOG],
      retentionPeriod: RetentionPeriod.CAMPAIGN_DURATION,
    },
    auditRequirement: AuditRequirement.BATCH,
    redTeamChallenges: [],
    doctrinalReferences: ['JP 2-0 Ch. II', 'ADP 2-0 para 1-6'],
    bastionMapping: {
      primaryPhase: 'Phase 3: Intelligence Framework',
      components: [
        { layer: 'backend', module: 'agents/fusion-agent.ts', existingCapability: true, requiredEnhancement: null },
        { layer: 'backend', module: 'agents/osint-monitor.ts', existingCapability: true, requiredEnhancement: null },
      ],
      implementationStatus: ImplementationStatus.PARTIALLY_IMPLEMENTED,
      gapAnalysis: 'Need MASINT/GEOINT connector pipelines',
    },
    dependsOn: [],
    enables: ['MDMP-0-02', 'MDMP-0-03', 'MDMP-0-04'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.FULL_COALITION,
      nationalCaveatSensitive: true,
      informationSharingLevel: SharingLevel.MISSION_PARTNERS,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-0-02',
    mdmpPhase: MDMPPhase.PHASE_0_CONTINUOUS,
    category: ActivityCategory.VALIDATION_CONSISTENCY,
    description: 'Cross-reference and deduplicate intelligence reports; flag contradictions across sources',
    authorityDesignation: AuthorityDesignation.AI_AUTONOMOUS,
    controlPosture: ControlPosture.FULLY_DELEGATED,
    daoTier: DAOTier.TACTICAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.ENTITY_RESOLUTION, AgentRole.CONFLICT_DETECTION],
      agentOutputType: AgentOutputType.VALIDATION_RESULT,
      humanCheckpoint: { required: false, trigger: 'never', requiredRole: null, timeoutMs: null },
      confidenceThreshold: 0,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.AUTOMATED_VALIDATION,
      blockchainRecord: true,
      teeRequired: false,
      evidenceTypes: [EvidenceType.VALIDATION_LOG],
      retentionPeriod: RetentionPeriod.CAMPAIGN_DURATION,
    },
    auditRequirement: AuditRequirement.BATCH,
    redTeamChallenges: [],
    doctrinalReferences: ['JP 2-0 Ch. III'],
    bastionMapping: {
      primaryPhase: 'Phase 3: Intelligence Framework',
      components: [
        { layer: 'backend', module: 'agents/entity-resolution.ts', existingCapability: true, requiredEnhancement: null },
        { layer: 'backend', module: 'agents/conflict-detection.ts', existingCapability: true, requiredEnhancement: null },
      ],
      implementationStatus: ImplementationStatus.PARTIALLY_IMPLEMENTED,
      gapAnalysis: null,
    },
    dependsOn: ['MDMP-0-01'],
    enables: ['MDMP-0-05', 'MDMP-2-01'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.US_ONLY,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.NATIONAL_ONLY,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-0-03',
    mdmpPhase: MDMPPhase.PHASE_0_CONTINUOUS,
    category: ActivityCategory.DATA_AGGREGATION,
    description: 'Normalize disparate data formats into common operational picture schema',
    authorityDesignation: AuthorityDesignation.AI_AUTONOMOUS,
    controlPosture: ControlPosture.FULLY_DELEGATED,
    daoTier: DAOTier.TACTICAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.STRATEGIC_FUSION],
      agentOutputType: AgentOutputType.VALIDATION_RESULT,
      humanCheckpoint: { required: false, trigger: 'never', requiredRole: null, timeoutMs: null },
      confidenceThreshold: 0,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.AUTOMATED_VALIDATION,
      blockchainRecord: false,
      teeRequired: false,
      evidenceTypes: [EvidenceType.VALIDATION_LOG],
      retentionPeriod: RetentionPeriod.STANDARD,
    },
    auditRequirement: AuditRequirement.BATCH,
    redTeamChallenges: [],
    doctrinalReferences: ['ADP 6-0 para 3-14'],
    bastionMapping: {
      primaryPhase: 'Phase 3: Intelligence Framework',
      components: [
        { layer: 'backend', module: 'agents/fusion-agent.ts', existingCapability: true, requiredEnhancement: 'Add COP schema normalization' },
      ],
      implementationStatus: ImplementationStatus.PLANNED,
      gapAnalysis: 'COP schema not yet defined',
    },
    dependsOn: ['MDMP-0-01'],
    enables: ['MDMP-0-04'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.FULL_COALITION,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.MISSION_PARTNERS,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-0-04',
    mdmpPhase: MDMPPhase.PHASE_0_CONTINUOUS,
    category: ActivityCategory.MONITORING,
    description: 'Continuous environmental monitoring: track OE changes, trigger alerts on threshold breaches',
    authorityDesignation: AuthorityDesignation.AI_AUTONOMOUS,
    controlPosture: ControlPosture.FULLY_DELEGATED,
    daoTier: DAOTier.TACTICAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.OSINT_MONITOR, AgentRole.COALITION_HEALTH],
      agentOutputType: AgentOutputType.ALERT,
      humanCheckpoint: { required: false, trigger: 'never', requiredRole: null, timeoutMs: null },
      confidenceThreshold: 0,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.AUTOMATED_VALIDATION,
      blockchainRecord: true,
      teeRequired: false,
      evidenceTypes: [EvidenceType.VALIDATION_LOG],
      retentionPeriod: RetentionPeriod.CAMPAIGN_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [],
    doctrinalReferences: ['JP 3-0 Ch. V', 'ADP 5-0 para 4-1'],
    bastionMapping: {
      primaryPhase: 'Phase 3: Intelligence Framework',
      components: [
        { layer: 'backend', module: 'agents/osint-monitor.ts', existingCapability: true, requiredEnhancement: 'Add threshold alerting' },
      ],
      implementationStatus: ImplementationStatus.PARTIALLY_IMPLEMENTED,
      gapAnalysis: 'Alert threshold configuration needed',
    },
    dependsOn: ['MDMP-0-01', 'MDMP-0-03'],
    enables: ['MDMP-1-01', 'MDMP-8-01'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.FULL_COALITION,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.MISSION_PARTNERS,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-0-05',
    mdmpPhase: MDMPPhase.PHASE_0_CONTINUOUS,
    category: ActivityCategory.META_COGNITIVE,
    description: 'Monitor AI agent output quality: detect drift, hallucination, stale data, confidence degradation',
    authorityDesignation: AuthorityDesignation.AI_AUTONOMOUS,
    controlPosture: ControlPosture.FULLY_DELEGATED,
    daoTier: DAOTier.TACTICAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.DATA_BIAS_DETECTOR],
      agentOutputType: AgentOutputType.BIAS_REPORT,
      humanCheckpoint: { required: false, trigger: 'never', requiredRole: null, timeoutMs: null },
      confidenceThreshold: 0,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.AUTOMATED_VALIDATION,
      blockchainRecord: true,
      teeRequired: true,
      evidenceTypes: [EvidenceType.VALIDATION_LOG, EvidenceType.CONFIDENCE_INTERVAL],
      retentionPeriod: RetentionPeriod.CAMPAIGN_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [],
    doctrinalReferences: ['DoD AI Strategy 2023'],
    bastionMapping: {
      primaryPhase: 'Phase 5.1: MDMP Governance Integration',
      components: [
        { layer: 'agent', module: 'agents/data-bias-detector.ts', existingCapability: false, requiredEnhancement: 'New agent' },
      ],
      implementationStatus: ImplementationStatus.NEW_REQUIREMENT,
      gapAnalysis: 'Meta-cognitive monitoring agent does not exist yet',
    },
    dependsOn: ['MDMP-0-02'],
    enables: ['MDMP-0-06'],
    minimumClassification: 'UNCLASSIFIED',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.US_ONLY,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.RELEASABLE,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-0-06',
    mdmpPhase: MDMPPhase.PHASE_0_CONTINUOUS,
    category: ActivityCategory.META_COGNITIVE,
    description: 'Track data staleness per source; flag intelligence products past expiration windows',
    authorityDesignation: AuthorityDesignation.AI_AUTONOMOUS,
    controlPosture: ControlPosture.FULLY_DELEGATED,
    daoTier: DAOTier.TACTICAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.DATA_BIAS_DETECTOR],
      agentOutputType: AgentOutputType.STALENESS_REPORT,
      humanCheckpoint: { required: false, trigger: 'never', requiredRole: null, timeoutMs: null },
      confidenceThreshold: 0,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.AUTOMATED_VALIDATION,
      blockchainRecord: false,
      teeRequired: false,
      evidenceTypes: [EvidenceType.VALIDATION_LOG],
      retentionPeriod: RetentionPeriod.STANDARD,
    },
    auditRequirement: AuditRequirement.BATCH,
    redTeamChallenges: [],
    doctrinalReferences: ['JP 2-0 Ch. IV'],
    bastionMapping: {
      primaryPhase: 'Phase 5.1: MDMP Governance Integration',
      components: [
        { layer: 'agent', module: 'agents/data-bias-detector.ts', existingCapability: false, requiredEnhancement: 'New agent' },
      ],
      implementationStatus: ImplementationStatus.NEW_REQUIREMENT,
      gapAnalysis: 'Staleness tracking not implemented',
    },
    dependsOn: ['MDMP-0-01'],
    enables: ['MDMP-2-01'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.US_ONLY,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.NATIONAL_ONLY,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-0-07',
    mdmpPhase: MDMPPhase.PHASE_0_CONTINUOUS,
    category: ActivityCategory.VALIDATION_CONSISTENCY,
    description: 'Validate format consistency of incoming orders, directives, and fragmentary orders',
    authorityDesignation: AuthorityDesignation.AI_AUTONOMOUS,
    controlPosture: ControlPosture.FULLY_DELEGATED,
    daoTier: DAOTier.TACTICAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.ORDERS_VALIDATOR],
      agentOutputType: AgentOutputType.VALIDATION_RESULT,
      humanCheckpoint: { required: false, trigger: 'never', requiredRole: null, timeoutMs: null },
      confidenceThreshold: 0,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.AUTOMATED_VALIDATION,
      blockchainRecord: true,
      teeRequired: false,
      evidenceTypes: [EvidenceType.VALIDATION_LOG],
      retentionPeriod: RetentionPeriod.MISSION_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [],
    doctrinalReferences: ['ADP 5-0 para 5-1'],
    bastionMapping: {
      primaryPhase: 'Phase 5.1: MDMP Governance Integration',
      components: [
        { layer: 'agent', module: 'agents/orders-validator.ts', existingCapability: false, requiredEnhancement: 'New agent' },
      ],
      implementationStatus: ImplementationStatus.NEW_REQUIREMENT,
      gapAnalysis: 'Orders validation agent does not exist yet',
    },
    dependsOn: [],
    enables: ['MDMP-1-01'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.US_ONLY,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.NATIONAL_ONLY,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  // ── AI Primary: Pattern Recognition ──
  {
    id: 'MDMP-0-08',
    mdmpPhase: MDMPPhase.PHASE_0_CONTINUOUS,
    category: ActivityCategory.PATTERN_RECOGNITION,
    description: 'Detect emerging threat patterns across intelligence domains; identify indicator changes',
    authorityDesignation: AuthorityDesignation.AI_PRIMARY,
    controlPosture: ControlPosture.HUMAN_OUT_OF_LOOP,
    daoTier: DAOTier.TACTICAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.STRATEGIC_FUSION, AgentRole.ADVERSARY_MODELER],
      agentOutputType: AgentOutputType.ANALYSIS_REPORT,
      humanCheckpoint: { required: true, trigger: 'on_exception', requiredRole: 'intelligence_officer', timeoutMs: 3600000 },
      confidenceThreshold: 0.7,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.AI_EXECUTION_PROOF,
      blockchainRecord: true,
      teeRequired: true,
      evidenceTypes: [EvidenceType.ANALYSIS_ARTIFACT, EvidenceType.CONFIDENCE_INTERVAL],
      retentionPeriod: RetentionPeriod.CAMPAIGN_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [
      {
        id: 'RT-0-01',
        question: 'What patterns would the adversary deliberately create to mislead our AI pattern recognition?',
        mdmpPhase: MDMPPhase.PHASE_0_CONTINUOUS,
        challengeType: ChallengeType.ADVERSARY_PERSPECTIVE,
        aiGeneratable: true,
        aiAnswerable: false,
        requiredResponseDepth: ResponseDepth.STRUCTURED_ANALYSIS,
        governanceGateLink: null,
        agentRole: AgentRole.DECEPTION_DETECTOR,
      },
    ],
    doctrinalReferences: ['JP 2-0 Ch. II', 'ADP 2-0 para 3-1'],
    bastionMapping: {
      primaryPhase: 'Phase 3: Intelligence Framework',
      components: [
        { layer: 'backend', module: 'agents/fusion-agent.ts', existingCapability: true, requiredEnhancement: 'Add pattern detection algorithms' },
        { layer: 'agent', module: 'agents/adversary-modeler.ts', existingCapability: false, requiredEnhancement: 'New agent' },
      ],
      implementationStatus: ImplementationStatus.GAP_IDENTIFIED,
      gapAnalysis: 'Adversary modeler agent needed for counter-pattern analysis',
    },
    dependsOn: ['MDMP-0-01', 'MDMP-0-02'],
    enables: ['MDMP-2-03', 'MDMP-2-08'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.MULTILATERAL,
      nationalCaveatSensitive: true,
      informationSharingLevel: SharingLevel.FIVE_EYES,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-0-09',
    mdmpPhase: MDMPPhase.PHASE_0_CONTINUOUS,
    category: ActivityCategory.MONITORING,
    description: 'Track coalition partner force posture changes and political indicators',
    authorityDesignation: AuthorityDesignation.AI_PRIMARY,
    controlPosture: ControlPosture.HUMAN_OUT_OF_LOOP,
    daoTier: DAOTier.STRATEGIC,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.COALITION_HEALTH, AgentRole.OSINT_MONITOR],
      agentOutputType: AgentOutputType.ALERT,
      humanCheckpoint: { required: true, trigger: 'on_exception', requiredRole: 'coalition_liaison', timeoutMs: 7200000 },
      confidenceThreshold: 0.6,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.AI_EXECUTION_PROOF,
      blockchainRecord: true,
      teeRequired: false,
      evidenceTypes: [EvidenceType.ANALYSIS_ARTIFACT],
      retentionPeriod: RetentionPeriod.CAMPAIGN_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [],
    doctrinalReferences: ['JP 3-16 Ch. II'],
    bastionMapping: {
      primaryPhase: 'Phase 12.1: Coalition Health Monitoring',
      components: [
        { layer: 'agent', module: 'agents/coalition-health.ts', existingCapability: false, requiredEnhancement: 'New agent' },
      ],
      implementationStatus: ImplementationStatus.NEW_REQUIREMENT,
      gapAnalysis: 'Coalition health monitoring agent does not exist',
    },
    dependsOn: ['MDMP-0-01'],
    enables: ['MDMP-2-14', 'MDMP-5-06'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.FULL_COALITION,
      nationalCaveatSensitive: true,
      informationSharingLevel: SharingLevel.NATO,
      partnerConcurrence: false,
      culturalSensitivity: true,
    },
  },
  {
    id: 'MDMP-0-10',
    mdmpPhase: MDMPPhase.PHASE_0_CONTINUOUS,
    category: ActivityCategory.META_COGNITIVE,
    description: 'Monitor assumption validity: check accepted assumptions against incoming intelligence',
    authorityDesignation: AuthorityDesignation.AI_AUTONOMOUS,
    controlPosture: ControlPosture.FULLY_DELEGATED,
    daoTier: DAOTier.OPERATIONAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.ASSUMPTION_AUDITOR],
      agentOutputType: AgentOutputType.ALERT,
      humanCheckpoint: { required: false, trigger: 'never', requiredRole: null, timeoutMs: null },
      confidenceThreshold: 0,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.AUTOMATED_VALIDATION,
      blockchainRecord: true,
      teeRequired: false,
      evidenceTypes: [EvidenceType.VALIDATION_LOG],
      retentionPeriod: RetentionPeriod.CAMPAIGN_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [],
    doctrinalReferences: ['ADP 5-0 para 2-14'],
    bastionMapping: {
      primaryPhase: 'Phase 5.1: MDMP Governance Integration',
      components: [
        { layer: 'agent', module: 'agents/assumption-auditor.ts', existingCapability: false, requiredEnhancement: 'New agent' },
        { layer: 'smart_contract', module: 'mdmp/assumptions.rs', existingCapability: false, requiredEnhancement: 'New contract' },
      ],
      implementationStatus: ImplementationStatus.NEW_REQUIREMENT,
      gapAnalysis: 'Assumption tracking system is entirely new',
    },
    dependsOn: ['MDMP-0-01'],
    enables: ['MDMP-2-13', 'MDMP-8-04'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.US_ONLY,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.NATIONAL_ONLY,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// PHASE 1: RECEIPT OF MISSION
// Transition from continuous monitoring to active planning.
// Mix of AI-led analysis and human authority decisions.
// ═══════════════════════════════════════════════════════════════════════════

export const PHASE_1_ACTIVITIES: MDMPActivity[] = [
  {
    id: 'MDMP-1-01',
    mdmpPhase: MDMPPhase.PHASE_1_RECEIPT,
    category: ActivityCategory.VALIDATION_CONSISTENCY,
    description: 'Parse and validate incoming WARNORD/OPORD for completeness, format compliance, and internal consistency',
    authorityDesignation: AuthorityDesignation.AI_AUTONOMOUS,
    controlPosture: ControlPosture.FULLY_DELEGATED,
    daoTier: DAOTier.OPERATIONAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.ORDERS_VALIDATOR],
      agentOutputType: AgentOutputType.VALIDATION_RESULT,
      humanCheckpoint: { required: false, trigger: 'never', requiredRole: null, timeoutMs: null },
      confidenceThreshold: 0,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.AUTOMATED_VALIDATION,
      blockchainRecord: true,
      teeRequired: false,
      evidenceTypes: [EvidenceType.VALIDATION_LOG],
      retentionPeriod: RetentionPeriod.MISSION_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [],
    doctrinalReferences: ['ADP 5-0 para 2-2', 'FM 6-0 Ch. 9'],
    bastionMapping: {
      primaryPhase: 'Phase 5.1: MDMP Governance Integration',
      components: [
        { layer: 'agent', module: 'agents/orders-validator.ts', existingCapability: false, requiredEnhancement: 'New agent' },
      ],
      implementationStatus: ImplementationStatus.NEW_REQUIREMENT,
      gapAnalysis: null,
    },
    dependsOn: ['MDMP-0-07'],
    enables: ['MDMP-1-02', 'MDMP-1-03'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.US_ONLY,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.NATIONAL_ONLY,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-1-02',
    mdmpPhase: MDMPPhase.PHASE_1_RECEIPT,
    category: ActivityCategory.DATA_AGGREGATION,
    description: 'Extract specified/implied tasks, constraints, and coordinating instructions from higher HQ order',
    authorityDesignation: AuthorityDesignation.AI_AUTONOMOUS,
    controlPosture: ControlPosture.FULLY_DELEGATED,
    daoTier: DAOTier.OPERATIONAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.RAFT_EXTRACTION],
      agentOutputType: AgentOutputType.ANALYSIS_REPORT,
      humanCheckpoint: { required: false, trigger: 'never', requiredRole: null, timeoutMs: null },
      confidenceThreshold: 0,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.AUTOMATED_VALIDATION,
      blockchainRecord: true,
      teeRequired: false,
      evidenceTypes: [EvidenceType.ANALYSIS_ARTIFACT],
      retentionPeriod: RetentionPeriod.MISSION_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [],
    doctrinalReferences: ['ADP 5-0 para 2-4', 'FM 6-0 para 9-8'],
    bastionMapping: {
      primaryPhase: 'Phase 4.2: RAFT Pipeline',
      components: [
        { layer: 'backend', module: 'agents/raft-extraction.ts', existingCapability: true, requiredEnhancement: 'Add task/constraint extraction templates' },
      ],
      implementationStatus: ImplementationStatus.PARTIALLY_IMPLEMENTED,
      gapAnalysis: 'RAFT extraction exists but lacks MDMP-specific templates',
    },
    dependsOn: ['MDMP-1-01'],
    enables: ['MDMP-1-04', 'MDMP-2-01'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.US_ONLY,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.NATIONAL_ONLY,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-1-03',
    mdmpPhase: MDMPPhase.PHASE_1_RECEIPT,
    category: ActivityCategory.MISSION_ANALYSIS,
    description: 'Generate initial timeline analysis: identify critical dates, phase transitions, decision points',
    authorityDesignation: AuthorityDesignation.HYBRID_AI_LED,
    controlPosture: ControlPosture.HUMAN_ON_LOOP,
    daoTier: DAOTier.OPERATIONAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.RAFT_REASONING, AgentRole.STRATEGIC_FUSION],
      agentOutputType: AgentOutputType.ANALYSIS_REPORT,
      humanCheckpoint: { required: true, trigger: 'always', requiredRole: 'chief_of_staff', timeoutMs: 7200000 },
      confidenceThreshold: 0.75,
      maxAutonomyOverride: true,
    },
    verification: {
      mechanism: VerificationMechanism.DUAL_VERIFICATION,
      blockchainRecord: true,
      teeRequired: true,
      evidenceTypes: [EvidenceType.ANALYSIS_ARTIFACT, EvidenceType.CONFIDENCE_INTERVAL],
      retentionPeriod: RetentionPeriod.MISSION_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [],
    doctrinalReferences: ['ADP 5-0 para 2-6'],
    bastionMapping: {
      primaryPhase: 'Phase 4.3: COA Analysis',
      components: [
        { layer: 'backend', module: 'agents/raft-reasoning.ts', existingCapability: true, requiredEnhancement: 'Add timeline analysis capability' },
      ],
      implementationStatus: ImplementationStatus.GAP_IDENTIFIED,
      gapAnalysis: 'Timeline analysis module needed in RAFT reasoning',
    },
    dependsOn: ['MDMP-1-01'],
    enables: ['MDMP-1-05', 'MDMP-2-05'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.MULTILATERAL,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.MISSION_PARTNERS,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-1-04',
    mdmpPhase: MDMPPhase.PHASE_1_RECEIPT,
    category: ActivityCategory.ASSUMPTION_MGMT,
    description: 'Surface initial planning assumptions from higher HQ order and standing plans',
    authorityDesignation: AuthorityDesignation.HYBRID_AI_LED,
    controlPosture: ControlPosture.HUMAN_ON_LOOP,
    daoTier: DAOTier.OPERATIONAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.ASSUMPTION_AUDITOR, AgentRole.RAFT_EXTRACTION],
      agentOutputType: AgentOutputType.GAP_ANALYSIS,
      humanCheckpoint: { required: true, trigger: 'always', requiredRole: 'planning_officer', timeoutMs: 3600000 },
      confidenceThreshold: 0.6,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.DUAL_VERIFICATION,
      blockchainRecord: true,
      teeRequired: false,
      evidenceTypes: [EvidenceType.ANALYSIS_ARTIFACT, EvidenceType.ASSUMPTION_ACCEPTANCE],
      retentionPeriod: RetentionPeriod.MISSION_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [
      {
        id: 'RT-1-01',
        question: 'What assumptions are we inheriting from higher HQ that we have not validated at our echelon?',
        mdmpPhase: MDMPPhase.PHASE_1_RECEIPT,
        challengeType: ChallengeType.ASSUMPTION_CHALLENGE,
        aiGeneratable: true,
        aiAnswerable: false,
        requiredResponseDepth: ResponseDepth.STRUCTURED_ANALYSIS,
        governanceGateLink: null,
        agentRole: AgentRole.ASSUMPTION_AUDITOR,
      },
    ],
    doctrinalReferences: ['ADP 5-0 para 2-14', 'JP 5-0 Ch. III para 10'],
    bastionMapping: {
      primaryPhase: 'Phase 5.1: MDMP Governance Integration',
      components: [
        { layer: 'agent', module: 'agents/assumption-auditor.ts', existingCapability: false, requiredEnhancement: 'New agent' },
        { layer: 'smart_contract', module: 'mdmp/assumptions.rs', existingCapability: false, requiredEnhancement: 'New contract' },
      ],
      implementationStatus: ImplementationStatus.NEW_REQUIREMENT,
      gapAnalysis: 'Assumption surfacing and tracking is entirely new capability',
    },
    dependsOn: ['MDMP-1-02'],
    enables: ['MDMP-2-13'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.US_ONLY,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.NATIONAL_ONLY,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-1-05',
    mdmpPhase: MDMPPhase.PHASE_1_RECEIPT,
    category: ActivityCategory.AUTHORITY_DECISION,
    description: 'Commander issues initial planning guidance: intent, focus areas, risk tolerance, timeline',
    authorityDesignation: AuthorityDesignation.HUMAN_ONLY,
    controlPosture: ControlPosture.HUMAN_EXCLUSIVE,
    daoTier: DAOTier.STRATEGIC,
    governanceGate: {
      required: true,
      gateType: GateType.AUTHORITY_CHECKPOINT,
      approvalThreshold: { approvalPercentage: 100, quorumPercentage: 100, vetoThreshold: null, unanimousRequired: true },
      vetoEnabled: false,
      coalitionApproval: false,
      timeConstraint: null,
      escalationPath: EscalationPath.HIGHER_DAO_TIER,
      bypassConditions: [
        { condition: 'FLASH_OVERRIDE', authorizedBy: 'commanding_general', auditRequired: true, maxDurationMs: null },
      ],
    },
    agentSupport: {
      enabled: false,
      agentPhase: 'Support',
      requiredAgents: [],
      agentOutputType: AgentOutputType.ANALYSIS_REPORT,
      humanCheckpoint: { required: true, trigger: 'always', requiredRole: 'commander', timeoutMs: null },
      confidenceThreshold: 1.0,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.HUMAN_ATTESTATION,
      blockchainRecord: true,
      teeRequired: false,
      evidenceTypes: [EvidenceType.DECISION_RECORD],
      retentionPeriod: RetentionPeriod.PERMANENT,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [],
    doctrinalReferences: ['ADP 5-0 para 2-8', 'ADP 6-0 para 1-3'],
    bastionMapping: {
      primaryPhase: 'Phase 5: DAO Governance',
      components: [
        { layer: 'smart_contract', module: 'dao/types.rs', existingCapability: true, requiredEnhancement: 'Add CommanderGuidance ProposalKind' },
        { layer: 'frontend', module: 'components/governance/commander-guidance.tsx', existingCapability: false, requiredEnhancement: 'New UI component' },
      ],
      implementationStatus: ImplementationStatus.GAP_IDENTIFIED,
      gapAnalysis: 'CommanderGuidance proposal type specified but not yet implemented',
    },
    dependsOn: ['MDMP-1-03'],
    enables: ['MDMP-2-01', 'MDMP-2-02'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.US_ONLY,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.NATIONAL_ONLY,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-1-06',
    mdmpPhase: MDMPPhase.PHASE_1_RECEIPT,
    category: ActivityCategory.AUTHORITY_DECISION,
    description: 'Approve staff estimates and allocate planning resources; issue initial planning timeline',
    authorityDesignation: AuthorityDesignation.HUMAN_ONLY,
    controlPosture: ControlPosture.HUMAN_EXCLUSIVE,
    daoTier: DAOTier.STRATEGIC,
    governanceGate: {
      required: true,
      gateType: GateType.PHASE_TRANSITION,
      approvalThreshold: { approvalPercentage: 67, quorumPercentage: 67, vetoThreshold: 33, unanimousRequired: false },
      vetoEnabled: true,
      coalitionApproval: false,
      timeConstraint: null,
      escalationPath: EscalationPath.COMMANDER_OVERRIDE,
      bypassConditions: [],
    },
    agentSupport: {
      enabled: false,
      agentPhase: 'Support',
      requiredAgents: [],
      agentOutputType: AgentOutputType.ANALYSIS_REPORT,
      humanCheckpoint: { required: true, trigger: 'always', requiredRole: 'commander', timeoutMs: null },
      confidenceThreshold: 1.0,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.HUMAN_ATTESTATION,
      blockchainRecord: true,
      teeRequired: false,
      evidenceTypes: [EvidenceType.DECISION_RECORD],
      retentionPeriod: RetentionPeriod.MISSION_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [],
    doctrinalReferences: ['ADP 5-0 para 2-10'],
    bastionMapping: {
      primaryPhase: 'Phase 5: DAO Governance',
      components: [
        { layer: 'smart_contract', module: 'mdmp/workflow.rs', existingCapability: false, requiredEnhancement: 'Phase transition gate' },
      ],
      implementationStatus: ImplementationStatus.NEW_REQUIREMENT,
      gapAnalysis: null,
    },
    dependsOn: ['MDMP-1-05'],
    enables: ['MDMP-2-01'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.US_ONLY,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.NATIONAL_ONLY,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// PHASE 2: MISSION ANALYSIS
// Heaviest analytical phase. Strong AI-led with human validation gates.
// ═══════════════════════════════════════════════════════════════════════════

export const PHASE_2_ACTIVITIES: MDMPActivity[] = [
  {
    id: 'MDMP-2-01',
    mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
    category: ActivityCategory.MISSION_ANALYSIS,
    description: 'Analyze higher HQ order and intent two levels up; identify essential tasks and purpose',
    authorityDesignation: AuthorityDesignation.HYBRID_AI_LED,
    controlPosture: ControlPosture.HUMAN_ON_LOOP,
    daoTier: DAOTier.OPERATIONAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.RAFT_REASONING, AgentRole.STRATEGIC_FUSION],
      agentOutputType: AgentOutputType.ANALYSIS_REPORT,
      humanCheckpoint: { required: true, trigger: 'always', requiredRole: 'planning_officer', timeoutMs: 7200000 },
      confidenceThreshold: 0.75,
      maxAutonomyOverride: true,
    },
    verification: {
      mechanism: VerificationMechanism.DUAL_VERIFICATION,
      blockchainRecord: true,
      teeRequired: true,
      evidenceTypes: [EvidenceType.ANALYSIS_ARTIFACT, EvidenceType.CONFIDENCE_INTERVAL],
      retentionPeriod: RetentionPeriod.MISSION_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [
      {
        id: 'RT-2-01',
        question: 'Are we interpreting higher commander intent correctly, or projecting our own assumptions?',
        mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
        challengeType: ChallengeType.ASSUMPTION_CHALLENGE,
        aiGeneratable: true,
        aiAnswerable: false,
        requiredResponseDepth: ResponseDepth.STRUCTURED_ANALYSIS,
        governanceGateLink: null,
        agentRole: AgentRole.ASSUMPTION_AUDITOR,
      },
    ],
    doctrinalReferences: ['ADP 5-0 para 2-12', 'JP 5-0 Ch. III para 5'],
    bastionMapping: {
      primaryPhase: 'Phase 4.2: RAFT Pipeline',
      components: [
        { layer: 'backend', module: 'agents/raft-reasoning.ts', existingCapability: true, requiredEnhancement: 'Add intent analysis templates' },
      ],
      implementationStatus: ImplementationStatus.PARTIALLY_IMPLEMENTED,
      gapAnalysis: 'Need MDMP-specific intent analysis prompts',
    },
    dependsOn: ['MDMP-1-02', 'MDMP-1-05', 'MDMP-1-06'],
    enables: ['MDMP-2-02', 'MDMP-2-03', 'MDMP-2-04'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.MULTILATERAL,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.MISSION_PARTNERS,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-2-02',
    mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
    category: ActivityCategory.PROBLEM_FRAMING,
    description: 'Frame the operational problem from multiple perspectives: adversary, coalition, civilian, information',
    authorityDesignation: AuthorityDesignation.HYBRID_HUMAN_LED,
    controlPosture: ControlPosture.HUMAN_IN_LOOP,
    daoTier: DAOTier.OPERATIONAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.PROBLEM_FRAMING, AgentRole.ADVERSARY_MODELER, AgentRole.NARRATIVE_IMPACT],
      agentOutputType: AgentOutputType.SCENARIO_SET,
      humanCheckpoint: { required: true, trigger: 'always', requiredRole: 'chief_of_staff', timeoutMs: 14400000 },
      confidenceThreshold: 0.6,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.DUAL_VERIFICATION,
      blockchainRecord: true,
      teeRequired: true,
      evidenceTypes: [EvidenceType.ANALYSIS_ARTIFACT, EvidenceType.CONFIDENCE_INTERVAL],
      retentionPeriod: RetentionPeriod.MISSION_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [
      {
        id: 'RT-2-02',
        question: 'What alternative problem framings are we not considering due to institutional bias?',
        mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
        challengeType: ChallengeType.INSTITUTIONAL_BIAS,
        aiGeneratable: true,
        aiAnswerable: true,
        requiredResponseDepth: ResponseDepth.STRUCTURED_ANALYSIS,
        governanceGateLink: null,
        agentRole: AgentRole.PROBLEM_FRAMING,
      },
      {
        id: 'RT-2-03',
        question: 'How would the adversary frame this problem? What do they see as our center of gravity?',
        mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
        challengeType: ChallengeType.ADVERSARY_PERSPECTIVE,
        aiGeneratable: true,
        aiAnswerable: true,
        requiredResponseDepth: ResponseDepth.STRUCTURED_ANALYSIS,
        governanceGateLink: null,
        agentRole: AgentRole.ADVERSARY_MODELER,
      },
    ],
    doctrinalReferences: ['ADP 5-0 para 2-15', 'JP 5-0 Ch. III para 6'],
    bastionMapping: {
      primaryPhase: 'Phase 5.1: MDMP Governance Integration',
      components: [
        { layer: 'agent', module: 'agents/problem-framing.ts', existingCapability: false, requiredEnhancement: 'New agent' },
        { layer: 'agent', module: 'agents/adversary-modeler.ts', existingCapability: false, requiredEnhancement: 'New agent' },
      ],
      implementationStatus: ImplementationStatus.NEW_REQUIREMENT,
      gapAnalysis: 'Problem framing and adversary modeling agents are new requirements',
    },
    dependsOn: ['MDMP-2-01'],
    enables: ['MDMP-2-05', 'MDMP-3-01'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.MULTILATERAL,
      nationalCaveatSensitive: true,
      informationSharingLevel: SharingLevel.FIVE_EYES,
      partnerConcurrence: false,
      culturalSensitivity: true,
    },
  },
  {
    id: 'MDMP-2-03',
    mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
    category: ActivityCategory.MISSION_ANALYSIS,
    description: 'Conduct IPB: weather, terrain, civil considerations, threat analysis with multi-domain integration',
    authorityDesignation: AuthorityDesignation.HYBRID_AI_LED,
    controlPosture: ControlPosture.HUMAN_ON_LOOP,
    daoTier: DAOTier.OPERATIONAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.STRATEGIC_FUSION, AgentRole.ADVERSARY_MODELER, AgentRole.OSINT_MONITOR],
      agentOutputType: AgentOutputType.ANALYSIS_REPORT,
      humanCheckpoint: { required: true, trigger: 'always', requiredRole: 'intelligence_officer', timeoutMs: 14400000 },
      confidenceThreshold: 0.7,
      maxAutonomyOverride: true,
    },
    verification: {
      mechanism: VerificationMechanism.DUAL_VERIFICATION,
      blockchainRecord: true,
      teeRequired: true,
      evidenceTypes: [EvidenceType.ANALYSIS_ARTIFACT, EvidenceType.CONFIDENCE_INTERVAL],
      retentionPeriod: RetentionPeriod.MISSION_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [
      {
        id: 'RT-2-04',
        question: 'What intelligence gaps in our IPB could the adversary exploit? Where are we data-poor?',
        mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
        challengeType: ChallengeType.BIAS_CHECK,
        aiGeneratable: true,
        aiAnswerable: true,
        requiredResponseDepth: ResponseDepth.STRUCTURED_ANALYSIS,
        governanceGateLink: null,
        agentRole: AgentRole.DATA_BIAS_DETECTOR,
      },
    ],
    doctrinalReferences: ['ATP 2-01.3', 'ADP 2-0 Ch. 3'],
    bastionMapping: {
      primaryPhase: 'Phase 3: Intelligence Framework',
      components: [
        { layer: 'backend', module: 'agents/fusion-agent.ts', existingCapability: true, requiredEnhancement: 'Add IPB analysis templates' },
        { layer: 'agent', module: 'agents/adversary-modeler.ts', existingCapability: false, requiredEnhancement: 'New agent' },
      ],
      implementationStatus: ImplementationStatus.GAP_IDENTIFIED,
      gapAnalysis: 'IPB analysis templates and adversary modeler needed',
    },
    dependsOn: ['MDMP-0-08', 'MDMP-2-01'],
    enables: ['MDMP-2-05', 'MDMP-2-06', 'MDMP-3-01'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.MULTILATERAL,
      nationalCaveatSensitive: true,
      informationSharingLevel: SharingLevel.FIVE_EYES,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-2-04',
    mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
    category: ActivityCategory.MISSION_ANALYSIS,
    description: 'Identify specified, implied, and essential tasks; determine mission-essential task list',
    authorityDesignation: AuthorityDesignation.HYBRID_AI_LED,
    controlPosture: ControlPosture.HUMAN_ON_LOOP,
    daoTier: DAOTier.OPERATIONAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.RAFT_EXTRACTION, AgentRole.RAFT_REASONING],
      agentOutputType: AgentOutputType.ANALYSIS_REPORT,
      humanCheckpoint: { required: true, trigger: 'always', requiredRole: 'planning_officer', timeoutMs: 7200000 },
      confidenceThreshold: 0.75,
      maxAutonomyOverride: true,
    },
    verification: {
      mechanism: VerificationMechanism.DUAL_VERIFICATION,
      blockchainRecord: true,
      teeRequired: true,
      evidenceTypes: [EvidenceType.ANALYSIS_ARTIFACT],
      retentionPeriod: RetentionPeriod.MISSION_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [],
    doctrinalReferences: ['ADP 5-0 para 2-16', 'FM 6-0 para 9-14'],
    bastionMapping: {
      primaryPhase: 'Phase 4.2: RAFT Pipeline',
      components: [
        { layer: 'backend', module: 'agents/raft-extraction.ts', existingCapability: true, requiredEnhancement: 'Add METL extraction' },
      ],
      implementationStatus: ImplementationStatus.PARTIALLY_IMPLEMENTED,
      gapAnalysis: 'Task extraction exists; METL derivation is new',
    },
    dependsOn: ['MDMP-2-01'],
    enables: ['MDMP-2-10', 'MDMP-3-01'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.MULTILATERAL,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.MISSION_PARTNERS,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-2-05',
    mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
    category: ActivityCategory.MISSION_ANALYSIS,
    description: 'Determine constraints, limitations, and freedoms of action from higher and adjacent HQ',
    authorityDesignation: AuthorityDesignation.HYBRID_AI_LED,
    controlPosture: ControlPosture.HUMAN_ON_LOOP,
    daoTier: DAOTier.OPERATIONAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.RAFT_EXTRACTION, AgentRole.ROE_COMPLIANCE],
      agentOutputType: AgentOutputType.COMPLIANCE_CHECK,
      humanCheckpoint: { required: true, trigger: 'always', requiredRole: 'legal_advisor', timeoutMs: 7200000 },
      confidenceThreshold: 0.8,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.DUAL_VERIFICATION,
      blockchainRecord: true,
      teeRequired: false,
      evidenceTypes: [EvidenceType.ANALYSIS_ARTIFACT, EvidenceType.COMPLIANCE_CHECK],
      retentionPeriod: RetentionPeriod.MISSION_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [],
    doctrinalReferences: ['ADP 5-0 para 2-18', 'FM 6-27'],
    bastionMapping: {
      primaryPhase: 'Phase 5.1: MDMP Governance Integration',
      components: [
        { layer: 'agent', module: 'agents/roe-compliance.ts', existingCapability: false, requiredEnhancement: 'New agent' },
      ],
      implementationStatus: ImplementationStatus.NEW_REQUIREMENT,
      gapAnalysis: 'ROE compliance agent is new requirement',
    },
    dependsOn: ['MDMP-1-03', 'MDMP-2-01'],
    enables: ['MDMP-2-06', 'MDMP-3-02'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.MULTILATERAL,
      nationalCaveatSensitive: true,
      informationSharingLevel: SharingLevel.MISSION_PARTNERS,
      partnerConcurrence: true,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-2-06',
    mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
    category: ActivityCategory.MISSION_ANALYSIS,
    description: 'Develop initial force ratio analysis; assess available forces vs. required capabilities by domain',
    authorityDesignation: AuthorityDesignation.HYBRID_AI_LED,
    controlPosture: ControlPosture.HUMAN_ON_LOOP,
    daoTier: DAOTier.OPERATIONAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.STRATEGIC_FUSION],
      agentOutputType: AgentOutputType.ANALYSIS_REPORT,
      humanCheckpoint: { required: true, trigger: 'always', requiredRole: 'operations_officer', timeoutMs: 7200000 },
      confidenceThreshold: 0.7,
      maxAutonomyOverride: true,
    },
    verification: {
      mechanism: VerificationMechanism.DUAL_VERIFICATION,
      blockchainRecord: true,
      teeRequired: true,
      evidenceTypes: [EvidenceType.ANALYSIS_ARTIFACT, EvidenceType.CONFIDENCE_INTERVAL],
      retentionPeriod: RetentionPeriod.MISSION_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [],
    doctrinalReferences: ['ADP 3-0 para 4-12', 'FM 6-0 para 9-20'],
    bastionMapping: {
      primaryPhase: 'Phase 4.3: COA Analysis',
      components: [
        { layer: 'backend', module: 'agents/fusion-agent.ts', existingCapability: true, requiredEnhancement: 'Add force ratio analysis' },
      ],
      implementationStatus: ImplementationStatus.GAP_IDENTIFIED,
      gapAnalysis: 'Force ratio analysis module needed',
    },
    dependsOn: ['MDMP-2-03', 'MDMP-2-05'],
    enables: ['MDMP-3-01', 'MDMP-3-03'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.MULTILATERAL,
      nationalCaveatSensitive: true,
      informationSharingLevel: SharingLevel.FIVE_EYES,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-2-07',
    mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
    category: ActivityCategory.MISSION_ANALYSIS,
    description: 'Generate CCIR: PIR, FFIR, and EEFI; link each to decision points and collection assets',
    authorityDesignation: AuthorityDesignation.HYBRID_AI_LED,
    controlPosture: ControlPosture.HUMAN_ON_LOOP,
    daoTier: DAOTier.OPERATIONAL,
    governanceGate: {
      required: true,
      gateType: GateType.PRODUCT_APPROVAL,
      approvalThreshold: { approvalPercentage: 67, quorumPercentage: 50, vetoThreshold: 33, unanimousRequired: false },
      vetoEnabled: true,
      coalitionApproval: false,
      timeConstraint: null,
      escalationPath: EscalationPath.CHIEF_OF_STAFF,
      bypassConditions: [],
    },
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.RAFT_REASONING, AgentRole.STRATEGIC_FUSION],
      agentOutputType: AgentOutputType.DRAFT_PRODUCT,
      humanCheckpoint: { required: true, trigger: 'always', requiredRole: 'intelligence_officer', timeoutMs: 14400000 },
      confidenceThreshold: 0.75,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.DUAL_VERIFICATION,
      blockchainRecord: true,
      teeRequired: true,
      evidenceTypes: [EvidenceType.ANALYSIS_ARTIFACT, EvidenceType.CONFIDENCE_INTERVAL],
      retentionPeriod: RetentionPeriod.MISSION_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [
      {
        id: 'RT-2-05',
        question: 'What information would the adversary deny us to cripple our CCIR? Are our collection plans resilient?',
        mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
        challengeType: ChallengeType.ADVERSARY_PERSPECTIVE,
        aiGeneratable: true,
        aiAnswerable: true,
        requiredResponseDepth: ResponseDepth.STRUCTURED_ANALYSIS,
        governanceGateLink: null,
        agentRole: AgentRole.ADVERSARY_MODELER,
      },
    ],
    doctrinalReferences: ['ADP 5-0 para 2-22', 'FM 6-0 para 9-28'],
    bastionMapping: {
      primaryPhase: 'Phase 4.2: RAFT Pipeline',
      components: [
        { layer: 'backend', module: 'agents/raft-reasoning.ts', existingCapability: true, requiredEnhancement: 'Add CCIR generation templates' },
      ],
      implementationStatus: ImplementationStatus.GAP_IDENTIFIED,
      gapAnalysis: 'CCIR generation capability needed in RAFT pipeline',
    },
    dependsOn: ['MDMP-2-01', 'MDMP-2-03'],
    enables: ['MDMP-2-10', 'MDMP-4-01'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.MULTILATERAL,
      nationalCaveatSensitive: true,
      informationSharingLevel: SharingLevel.FIVE_EYES,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-2-08',
    mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
    category: ActivityCategory.INTENT_ASSESSMENT,
    description: 'Develop adversary most likely COA (MLCOA) and most dangerous COA (MDCOA)',
    authorityDesignation: AuthorityDesignation.HYBRID_HUMAN_LED,
    controlPosture: ControlPosture.HUMAN_IN_LOOP,
    daoTier: DAOTier.OPERATIONAL,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.ADVERSARY_MODELER, AgentRole.DECEPTION_DETECTOR],
      agentOutputType: AgentOutputType.SCENARIO_SET,
      humanCheckpoint: { required: true, trigger: 'always', requiredRole: 'intelligence_officer', timeoutMs: 14400000 },
      confidenceThreshold: 0.6,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.DUAL_VERIFICATION,
      blockchainRecord: true,
      teeRequired: true,
      evidenceTypes: [EvidenceType.ANALYSIS_ARTIFACT, EvidenceType.CONFIDENCE_INTERVAL],
      retentionPeriod: RetentionPeriod.MISSION_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [
      {
        id: 'RT-2-06',
        question: 'Are we mirror-imaging the adversary? What culturally-specific COAs are we missing?',
        mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
        challengeType: ChallengeType.ADVERSARY_PERSPECTIVE,
        aiGeneratable: true,
        aiAnswerable: false,
        requiredResponseDepth: ResponseDepth.WARGAME_TESTED,
        governanceGateLink: null,
        agentRole: AgentRole.ADVERSARY_MODELER,
      },
    ],
    doctrinalReferences: ['ATP 2-01.3 Ch. 6', 'ADP 2-0 para 3-8'],
    bastionMapping: {
      primaryPhase: 'Phase 5.2: Escalation & Competition Modeling',
      components: [
        { layer: 'agent', module: 'agents/adversary-modeler.ts', existingCapability: false, requiredEnhancement: 'New agent' },
        { layer: 'agent', module: 'agents/deception-detector.ts', existingCapability: false, requiredEnhancement: 'New agent' },
      ],
      implementationStatus: ImplementationStatus.NEW_REQUIREMENT,
      gapAnalysis: 'Adversary modeling and deception detection are new capabilities',
    },
    dependsOn: ['MDMP-0-08', 'MDMP-2-03'],
    enables: ['MDMP-3-01', 'MDMP-4-01'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.MULTILATERAL,
      nationalCaveatSensitive: true,
      informationSharingLevel: SharingLevel.FIVE_EYES,
      partnerConcurrence: false,
      culturalSensitivity: true,
    },
  },
  {
    id: 'MDMP-2-09',
    mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
    category: ActivityCategory.ETHICAL_LEGAL,
    description: 'Review ROE applicability; identify legal constraints on potential COAs; advise on LOAC compliance',
    authorityDesignation: AuthorityDesignation.HUMAN_ONLY,
    controlPosture: ControlPosture.HUMAN_EXCLUSIVE,
    daoTier: DAOTier.STRATEGIC,
    governanceGate: null,
    agentSupport: {
      enabled: false,
      agentPhase: 'Support',
      requiredAgents: [],
      agentOutputType: AgentOutputType.COMPLIANCE_CHECK,
      humanCheckpoint: { required: true, trigger: 'always', requiredRole: 'legal_advisor', timeoutMs: null },
      confidenceThreshold: 1.0,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.HUMAN_ATTESTATION,
      blockchainRecord: true,
      teeRequired: false,
      evidenceTypes: [EvidenceType.DECISION_RECORD],
      retentionPeriod: RetentionPeriod.PERMANENT,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [],
    doctrinalReferences: ['FM 6-27', 'DoD Law of War Manual'],
    bastionMapping: {
      primaryPhase: 'Phase 5: DAO Governance',
      components: [
        { layer: 'smart_contract', module: 'dao/types.rs', existingCapability: true, requiredEnhancement: null },
      ],
      implementationStatus: ImplementationStatus.FULLY_IMPLEMENTED,
      gapAnalysis: null,
    },
    dependsOn: ['MDMP-2-05'],
    enables: ['MDMP-3-02', 'MDMP-7-04'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.MULTILATERAL,
      nationalCaveatSensitive: true,
      informationSharingLevel: SharingLevel.MISSION_PARTNERS,
      partnerConcurrence: true,
      culturalSensitivity: true,
    },
  },
  {
    id: 'MDMP-2-10',
    mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
    category: ActivityCategory.MISSION_ANALYSIS,
    description: 'Draft restated mission statement incorporating essential tasks, purpose, and endstate',
    authorityDesignation: AuthorityDesignation.HYBRID_AI_LED,
    controlPosture: ControlPosture.HUMAN_ON_LOOP,
    daoTier: DAOTier.OPERATIONAL,
    governanceGate: {
      required: true,
      gateType: GateType.PRODUCT_APPROVAL,
      approvalThreshold: { approvalPercentage: 67, quorumPercentage: 67, vetoThreshold: 33, unanimousRequired: false },
      vetoEnabled: true,
      coalitionApproval: false,
      timeConstraint: null,
      escalationPath: EscalationPath.COMMANDER_OVERRIDE,
      bypassConditions: [],
    },
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.RAFT_REASONING],
      agentOutputType: AgentOutputType.DRAFT_PRODUCT,
      humanCheckpoint: { required: true, trigger: 'always', requiredRole: 'commander', timeoutMs: 14400000 },
      confidenceThreshold: 0.8,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.DUAL_VERIFICATION,
      blockchainRecord: true,
      teeRequired: true,
      evidenceTypes: [EvidenceType.ANALYSIS_ARTIFACT, EvidenceType.DECISION_RECORD],
      retentionPeriod: RetentionPeriod.MISSION_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [],
    doctrinalReferences: ['ADP 5-0 para 2-24', 'FM 6-0 para 9-34'],
    bastionMapping: {
      primaryPhase: 'Phase 4.2: RAFT Pipeline',
      components: [
        { layer: 'backend', module: 'agents/raft-reasoning.ts', existingCapability: true, requiredEnhancement: 'Add mission statement generation' },
        { layer: 'smart_contract', module: 'mdmp/workflow.rs', existingCapability: false, requiredEnhancement: 'Product approval gate' },
      ],
      implementationStatus: ImplementationStatus.GAP_IDENTIFIED,
      gapAnalysis: 'Mission statement generation template and product approval gate needed',
    },
    dependsOn: ['MDMP-2-04', 'MDMP-2-07'],
    enables: ['MDMP-2-11'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.MULTILATERAL,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.MISSION_PARTNERS,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-2-11',
    mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
    category: ActivityCategory.AUTHORITY_DECISION,
    description: 'Commander approves restated mission; issues updated planning guidance',
    authorityDesignation: AuthorityDesignation.HUMAN_ONLY,
    controlPosture: ControlPosture.HUMAN_EXCLUSIVE,
    daoTier: DAOTier.STRATEGIC,
    governanceGate: {
      required: true,
      gateType: GateType.AUTHORITY_CHECKPOINT,
      approvalThreshold: { approvalPercentage: 100, quorumPercentage: 100, vetoThreshold: null, unanimousRequired: true },
      vetoEnabled: false,
      coalitionApproval: false,
      timeConstraint: null,
      escalationPath: EscalationPath.HIGHER_DAO_TIER,
      bypassConditions: [],
    },
    agentSupport: {
      enabled: false,
      agentPhase: 'Support',
      requiredAgents: [],
      agentOutputType: AgentOutputType.ANALYSIS_REPORT,
      humanCheckpoint: { required: true, trigger: 'always', requiredRole: 'commander', timeoutMs: null },
      confidenceThreshold: 1.0,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.HUMAN_ATTESTATION,
      blockchainRecord: true,
      teeRequired: false,
      evidenceTypes: [EvidenceType.DECISION_RECORD],
      retentionPeriod: RetentionPeriod.PERMANENT,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [],
    doctrinalReferences: ['ADP 5-0 para 2-26'],
    bastionMapping: {
      primaryPhase: 'Phase 5: DAO Governance',
      components: [
        { layer: 'smart_contract', module: 'dao/types.rs', existingCapability: true, requiredEnhancement: 'CommanderGuidance ProposalKind' },
        { layer: 'smart_contract', module: 'mdmp/workflow.rs', existingCapability: false, requiredEnhancement: 'Authority checkpoint gate' },
      ],
      implementationStatus: ImplementationStatus.GAP_IDENTIFIED,
      gapAnalysis: 'Commander approval flow needs MDMP workflow integration',
    },
    dependsOn: ['MDMP-2-10'],
    enables: ['MDMP-3-01'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.US_ONLY,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.NATIONAL_ONLY,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-2-12',
    mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
    category: ActivityCategory.RISK_JUDGMENT,
    description: 'Identify initial risks to mission and force; establish risk mitigation priorities',
    authorityDesignation: AuthorityDesignation.HUMAN_ONLY,
    controlPosture: ControlPosture.HUMAN_EXCLUSIVE,
    daoTier: DAOTier.STRATEGIC,
    governanceGate: null,
    agentSupport: {
      enabled: false,
      agentPhase: 'Support',
      requiredAgents: [],
      agentOutputType: AgentOutputType.ANALYSIS_REPORT,
      humanCheckpoint: { required: true, trigger: 'always', requiredRole: 'commander', timeoutMs: null },
      confidenceThreshold: 1.0,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.HUMAN_ATTESTATION,
      blockchainRecord: true,
      teeRequired: false,
      evidenceTypes: [EvidenceType.RISK_ACCEPTANCE, EvidenceType.DECISION_RECORD],
      retentionPeriod: RetentionPeriod.PERMANENT,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [],
    doctrinalReferences: ['ADP 5-0 para 2-28', 'ATP 5-19'],
    bastionMapping: {
      primaryPhase: 'Phase 5: DAO Governance',
      components: [
        { layer: 'smart_contract', module: 'dao/types.rs', existingCapability: true, requiredEnhancement: null },
      ],
      implementationStatus: ImplementationStatus.FULLY_IMPLEMENTED,
      gapAnalysis: null,
    },
    dependsOn: ['MDMP-2-03', 'MDMP-2-06'],
    enables: ['MDMP-3-02'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.US_ONLY,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.NATIONAL_ONLY,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-2-13',
    mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
    category: ActivityCategory.ASSUMPTION_MGMT,
    description: 'Formally accept/reject planning assumptions; assign risk owners; record on blockchain',
    authorityDesignation: AuthorityDesignation.HUMAN_ONLY,
    controlPosture: ControlPosture.HUMAN_EXCLUSIVE,
    daoTier: DAOTier.OPERATIONAL,
    governanceGate: {
      required: true,
      gateType: GateType.ASSUMPTION_GATE,
      approvalThreshold: { approvalPercentage: 50, quorumPercentage: 50, vetoThreshold: null, unanimousRequired: false },
      vetoEnabled: false,
      coalitionApproval: false,
      timeConstraint: null,
      escalationPath: EscalationPath.COMMANDER_OVERRIDE,
      bypassConditions: [],
    },
    agentSupport: {
      enabled: false,
      agentPhase: 'Support',
      requiredAgents: [],
      agentOutputType: AgentOutputType.ANALYSIS_REPORT,
      humanCheckpoint: { required: true, trigger: 'always', requiredRole: 'planning_officer', timeoutMs: null },
      confidenceThreshold: 1.0,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.HUMAN_ATTESTATION,
      blockchainRecord: true,
      teeRequired: false,
      evidenceTypes: [EvidenceType.ASSUMPTION_ACCEPTANCE, EvidenceType.DECISION_RECORD],
      retentionPeriod: RetentionPeriod.MISSION_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [
      {
        id: 'RT-2-07',
        question: 'Which accepted assumptions are we treating as facts? What would invalidate our most critical assumption?',
        mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
        challengeType: ChallengeType.ASSUMPTION_CHALLENGE,
        aiGeneratable: true,
        aiAnswerable: false,
        requiredResponseDepth: ResponseDepth.STRUCTURED_ANALYSIS,
        governanceGateLink: 'assumption_gate_phase_2',
        agentRole: AgentRole.ASSUMPTION_AUDITOR,
      },
    ],
    doctrinalReferences: ['ADP 5-0 para 2-14', 'JP 5-0 Ch. III para 10'],
    bastionMapping: {
      primaryPhase: 'Phase 5.1: MDMP Governance Integration',
      components: [
        { layer: 'smart_contract', module: 'mdmp/assumptions.rs', existingCapability: false, requiredEnhancement: 'New contract' },
        { layer: 'frontend', module: 'components/governance/assumption-panel.tsx', existingCapability: false, requiredEnhancement: 'New UI component' },
      ],
      implementationStatus: ImplementationStatus.NEW_REQUIREMENT,
      gapAnalysis: 'Assumption registry contract and UI are entirely new',
    },
    dependsOn: ['MDMP-1-04', 'MDMP-0-10'],
    enables: ['MDMP-3-01', 'MDMP-8-04'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.US_ONLY,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.NATIONAL_ONLY,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
  {
    id: 'MDMP-2-14',
    mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
    category: ActivityCategory.COALITION_MGMT,
    description: 'Assess coalition partner capabilities, constraints, and national caveats; identify integration requirements',
    authorityDesignation: AuthorityDesignation.HYBRID_HUMAN_LED,
    controlPosture: ControlPosture.HUMAN_IN_LOOP,
    daoTier: DAOTier.STRATEGIC,
    governanceGate: null,
    agentSupport: {
      enabled: true,
      agentPhase: 'Support',
      requiredAgents: [AgentRole.COALITION_HEALTH],
      agentOutputType: AgentOutputType.ANALYSIS_REPORT,
      humanCheckpoint: { required: true, trigger: 'always', requiredRole: 'coalition_liaison', timeoutMs: 28800000 },
      confidenceThreshold: 0.5,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.DUAL_VERIFICATION,
      blockchainRecord: true,
      teeRequired: false,
      evidenceTypes: [EvidenceType.ANALYSIS_ARTIFACT, EvidenceType.COALITION_CONCURRENCE],
      retentionPeriod: RetentionPeriod.CAMPAIGN_DURATION,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [
      {
        id: 'RT-2-08',
        question: 'Which coalition partner is most likely to defect or impose new caveats under stress? What is our fallback?',
        mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
        challengeType: ChallengeType.COALITION_STRESS,
        aiGeneratable: true,
        aiAnswerable: false,
        requiredResponseDepth: ResponseDepth.STRUCTURED_ANALYSIS,
        governanceGateLink: null,
        agentRole: AgentRole.COALITION_HEALTH,
      },
    ],
    doctrinalReferences: ['JP 3-16 Ch. III', 'ADP 3-0 para 5-6'],
    bastionMapping: {
      primaryPhase: 'Phase 12.1: Coalition Health Monitoring',
      components: [
        { layer: 'agent', module: 'agents/coalition-health.ts', existingCapability: false, requiredEnhancement: 'New agent' },
        { layer: 'smart_contract', module: 'dao/linkages.rs', existingCapability: true, requiredEnhancement: 'Add national caveat tracking' },
      ],
      implementationStatus: ImplementationStatus.GAP_IDENTIFIED,
      gapAnalysis: 'Coalition linkages exist but lack caveat tracking and health monitoring',
    },
    dependsOn: ['MDMP-0-09', 'MDMP-2-03'],
    enables: ['MDMP-3-03', 'MDMP-5-06'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.FULL_COALITION,
      nationalCaveatSensitive: true,
      informationSharingLevel: SharingLevel.NATO,
      partnerConcurrence: true,
      culturalSensitivity: true,
    },
  },
  {
    id: 'MDMP-2-15',
    mdmpPhase: MDMPPhase.PHASE_2_ANALYSIS,
    category: ActivityCategory.AUTHORITY_DECISION,
    description: 'Phase 2 completion: Commander approves mission analysis brief; authorize transition to COA Development',
    authorityDesignation: AuthorityDesignation.HUMAN_ONLY,
    controlPosture: ControlPosture.HUMAN_EXCLUSIVE,
    daoTier: DAOTier.STRATEGIC,
    governanceGate: {
      required: true,
      gateType: GateType.PHASE_TRANSITION,
      approvalThreshold: { approvalPercentage: 67, quorumPercentage: 67, vetoThreshold: 33, unanimousRequired: false },
      vetoEnabled: true,
      coalitionApproval: false,
      timeConstraint: null,
      escalationPath: EscalationPath.COMMANDER_OVERRIDE,
      bypassConditions: [
        { condition: 'FLASH_OVERRIDE', authorizedBy: 'commanding_general', auditRequired: true, maxDurationMs: null },
      ],
    },
    agentSupport: {
      enabled: false,
      agentPhase: 'Support',
      requiredAgents: [],
      agentOutputType: AgentOutputType.ANALYSIS_REPORT,
      humanCheckpoint: { required: true, trigger: 'always', requiredRole: 'commander', timeoutMs: null },
      confidenceThreshold: 1.0,
      maxAutonomyOverride: false,
    },
    verification: {
      mechanism: VerificationMechanism.HUMAN_ATTESTATION,
      blockchainRecord: true,
      teeRequired: false,
      evidenceTypes: [EvidenceType.DECISION_RECORD, EvidenceType.VOTE_RECORD],
      retentionPeriod: RetentionPeriod.PERMANENT,
    },
    auditRequirement: AuditRequirement.REAL_TIME,
    redTeamChallenges: [],
    doctrinalReferences: ['ADP 5-0 para 2-30'],
    bastionMapping: {
      primaryPhase: 'Phase 5.1: MDMP Governance Integration',
      components: [
        { layer: 'smart_contract', module: 'mdmp/workflow.rs', existingCapability: false, requiredEnhancement: 'Phase transition gate' },
      ],
      implementationStatus: ImplementationStatus.NEW_REQUIREMENT,
      gapAnalysis: null,
    },
    dependsOn: ['MDMP-2-10', 'MDMP-2-11', 'MDMP-2-13'],
    enables: ['MDMP-3-01'],
    minimumClassification: 'SECRET',
    coalitionRelevance: {
      coalitionImpact: CoalitionImpact.US_ONLY,
      nationalCaveatSensitive: false,
      informationSharingLevel: SharingLevel.NATIONAL_ONLY,
      partnerConcurrence: false,
      culturalSensitivity: false,
    },
  },
];
