/**
 * AIContextSnapshotModal
 *
 * Modal overlay showing the AI context summary for the strategic environment
 * at the brain's current time scale. Users can save a snapshot for historical
 * reference and view/delete previously saved snapshots.
 *
 * Saved snapshots are injected into StrategicContextService.assembleContext()
 * making them available as "source of truth" to all BASTION AI agents.
 */

import React, { useState, useEffect, useCallback, useRef } from 'react';
import './AIContextSnapshotModal.css';
import { useBrainSnapshots } from './hooks/useBrainSnapshots.js';
import type { BrainSnapshot } from './hooks/useBrainSnapshots.js';

const BACKEND_URL = import.meta.env.VITE_API_URL ?? '';

// ─── Types ────────────────────────────────────────────────────────────────────

interface AIContextSnapshotModalProps {
  isOpen: boolean;
  onClose: () => void;
  problemSetId: string;
  /** Precomputed AI context summary — generated by the strategic context service */
  currentSummary?: string;
  nodeCount: number;
  edgeCount: number;
  currentTimeScale?: Date;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function formatDate(isoString: string): string {
  const d = new Date(isoString);
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

function formatTimeScale(date?: Date): string {
  if (!date) return 'Current';
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit' });
}

function defaultSnapshotTitle(): string {
  const now = new Date();
  return `Snapshot - ${now.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`;
}

// ─── Executive Briefing Builder ───────────────────────────────────────────────

interface DocSummary {
  title?: string;
  docType?: string;
  extractedData?: {
    summary?: string;
    classification?: string;
    objectiveCount?: number;
    objectives?: Array<{
      description?: string;
      instrument?: string;
      priority?: string;
      assumptions?: string[];
      risks?: string[];
    }>;
  };
  textContent?: string;
}

interface DecisionInfo {
  totalDecisions?: number;
  knowledgeGapCount?: number;
  recentDecisions?: Array<{
    title?: string;
    outcome?: string;
    basis?: string;
    knowledgeGaps?: string[];
  }>;
}

/**
 * Build a structured executive briefing from raw strategic context.
 * Produces a narrative organized into: Situation, Key Actors, Objectives,
 * Decision Status, Intelligence Gaps, and Source Assessment.
 */
function buildExecutiveBriefing(ctx: Record<string, unknown>): string {
  const sections: string[] = [];

  // ── 1. Strategic Situation (from graph summaries) ──────────────────────
  const graphs = ctx.graphSummaries as Record<string, {
    summary?: string;
    title?: string;
    topActors?: Array<{ name: string; category?: string }>;
    activeTensions?: Array<{ description: string; intensity?: string }>;
    annotationCount?: number;
  }> | undefined;

  const situationParts: string[] = [];
  const allActors: Array<{ name: string; category?: string }> = [];
  const allTensions: Array<{ description: string; intensity?: string }> = [];

  if (graphs) {
    for (const [key, gs] of Object.entries(graphs)) {
      if (key === '__brain_snapshot' && gs.summary) {
        // Use saved snapshot as the baseline situation assessment
        situationParts.unshift(gs.summary);
        continue;
      }
      if (key === '__brain_annotations') continue; // handled separately
      if (gs.summary) situationParts.push(gs.summary);
      if (gs.topActors) allActors.push(...gs.topActors);
      if (gs.activeTensions) allTensions.push(...gs.activeTensions);
    }
  }

  if (situationParts.length > 0) {
    sections.push(`STRATEGIC SITUATION\n${situationParts.join(' ')}`);
  }

  // ── 2. Key Actors ─────────────────────────────────────────────────────
  if (allActors.length > 0) {
    const grouped: Record<string, string[]> = {};
    for (const actor of allActors) {
      const cat = actor.category ?? 'other';
      if (!grouped[cat]) grouped[cat] = [];
      if (!grouped[cat].includes(actor.name)) grouped[cat].push(actor.name);
    }
    const actorLines = Object.entries(grouped)
      .map(([cat, names]) => `  ${cat.toUpperCase()}: ${names.join(', ')}`)
      .join('\n');
    sections.push(`KEY ACTORS\n${actorLines}`);
  }

  // ── 3. Active Tensions ────────────────────────────────────────────────
  if (allTensions.length > 0) {
    const tensionLines = allTensions
      .slice(0, 5)
      .map((t, i) => `  ${i + 1}. ${t.description}${t.intensity ? ` [Intensity: ${t.intensity}]` : ''}`)
      .join('\n');
    sections.push(`ACTIVE TENSIONS\n${tensionLines}`);
  }

  // ── 4. Strategic Objectives (from document extractions) ───────────────
  const docs = ctx.documentSummaries as DocSummary[] | undefined;
  if (Array.isArray(docs) && docs.length > 0) {
    const allObjectives: Array<{ description: string; instrument: string; priority: string; source: string }> = [];

    for (const doc of docs) {
      if (doc.extractedData?.objectives) {
        for (const obj of doc.extractedData.objectives) {
          if (obj.description) {
            allObjectives.push({
              description: obj.description,
              instrument: obj.instrument ?? 'unknown',
              priority: obj.priority ?? 'MEDIUM',
              source: doc.title ?? 'Unknown',
            });
          }
        }
      }
    }

    if (allObjectives.length > 0) {
      // Group by DIME instrument
      const byInstrument: Record<string, typeof allObjectives> = {};
      for (const obj of allObjectives) {
        const key = obj.instrument.toUpperCase();
        if (!byInstrument[key]) byInstrument[key] = [];
        byInstrument[key].push(obj);
      }

      const objLines: string[] = [];
      for (const [instrument, objs] of Object.entries(byInstrument)) {
        objLines.push(`  ${instrument}:`);
        for (const obj of objs.slice(0, 5)) {
          const priorityTag = obj.priority !== 'MEDIUM' ? ` [${obj.priority}]` : '';
          objLines.push(`    - ${obj.description.slice(0, 120)}${priorityTag}`);
        }
      }
      sections.push(`STRATEGIC OBJECTIVES (${allObjectives.length} extracted)\n${objLines.join('\n')}`);
    }

    // ── 5. Source Assessment ─────────────────────────────────────────────
    const docLines = docs.map(d => {
      const objCount = d.extractedData?.objectiveCount ?? 0;
      const cls = d.extractedData?.classification ?? 'UNCLASSIFIED';
      const status = objCount > 0
        ? `${objCount} objectives extracted`
        : 'Pending analysis';
      return `  - ${d.title ?? 'Untitled'} (${cls}) — ${status}`;
    });
    sections.push(`SOURCE DOCUMENTS (${docs.length})\n${docLines.join('\n')}`);

    // Include document text summaries if no objectives were found
    if (allObjectives.length === 0) {
      const textSummaries: string[] = [];
      for (const doc of docs.slice(0, 3)) {
        const summary = doc.extractedData?.summary || doc.textContent;
        if (summary) {
          const truncated = summary.length > 300 ? summary.slice(0, 297) + '...' : summary;
          textSummaries.push(`  ${doc.title ?? 'Document'}: ${truncated}`);
        }
      }
      if (textSummaries.length > 0) {
        sections.push(`DOCUMENT SUMMARIES\n${textSummaries.join('\n\n')}`);
      }
    }
  }

  // ── 6. Decision Status & Knowledge Gaps ────────────────────────────────
  const decisions = ctx.decisionSummary as DecisionInfo | undefined;
  if (decisions && decisions.totalDecisions && decisions.totalDecisions > 0) {
    const decParts: string[] = [];
    decParts.push(`  ${decisions.totalDecisions} decisions recorded, ${decisions.knowledgeGapCount ?? 0} with identified knowledge gaps.`);

    if (decisions.recentDecisions && decisions.recentDecisions.length > 0) {
      decParts.push('');
      decParts.push('  Recent decisions:');
      for (const dec of decisions.recentDecisions.slice(0, 5)) {
        decParts.push(`    - ${dec.title ?? 'Untitled'}: ${dec.outcome ?? 'pending'} (basis: ${dec.basis ?? 'unknown'})`);
        if (dec.knowledgeGaps && dec.knowledgeGaps.length > 0) {
          decParts.push(`      Gaps: ${dec.knowledgeGaps.join('; ')}`);
        }
      }
    }
    sections.push(`DECISION STATUS\n${decParts.join('\n')}`);
  }

  // ── 7. Analyst Annotations ─────────────────────────────────────────────
  if (graphs?.['__brain_annotations']) {
    const annotSummary = (graphs['__brain_annotations'] as unknown as { summary?: string }).summary;
    if (annotSummary) {
      sections.push(`ANALYST NOTES\n${annotSummary}`);
    }
  }

  // ── Final assembly ─────────────────────────────────────────────────────
  if (sections.length === 0) {
    return 'No strategic context has been generated yet.\n\nTo populate this briefing:\n1. Upload strategic documents in the Understand tab\n2. Run document analysis to extract objectives\n3. Build actor relationships in the knowledge graph\n\nThe briefing will automatically synthesize available intelligence into an executive summary.';
  }

  return `EXECUTIVE BRIEFING — ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}\n\n${sections.join('\n\n')}`;
}

// ─── Component ────────────────────────────────────────────────────────────────

export function AIContextSnapshotModal({
  isOpen,
  onClose,
  problemSetId,
  currentSummary,
  nodeCount,
  edgeCount,
  currentTimeScale,
}: AIContextSnapshotModalProps): React.ReactElement | null {
  const { snapshots, loading: snapshotsLoading, saveSnapshot, deleteSnapshot } = useBrainSnapshots(problemSetId);

  const [fetchedSummary, setFetchedSummary] = useState<string | null>(null);
  const [summaryLoading, setSummaryLoading] = useState(false);

  const [snapshotTitle, setSnapshotTitle] = useState(defaultSnapshotTitle);
  const [saving, setSaving] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);

  const [expandedSnapshotId, setExpandedSnapshotId] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);

  const modalRef = useRef<HTMLDivElement>(null);

  // Fetch context summary if not provided as prop
  useEffect(() => {
    if (!isOpen || currentSummary) return;

    setSummaryLoading(true);
    fetch(`${BACKEND_URL}/api/strategic-context/preview/${encodeURIComponent(problemSetId)}`)
      .then((res) => {
        if (!res.ok) throw new Error(`Failed to load context: ${res.status}`);
        return res.json() as Promise<{ context?: Record<string, unknown> | string | null }>;
      })
      .then((data) => {
        if (!data.context) {
          setFetchedSummary('No context available — add strategic documents or subscribe to a parent problem set.');
        } else if (typeof data.context === 'string') {
          setFetchedSummary(data.context);
        } else {
          // Build an executive briefing from the structured context
          const ctx = data.context as Record<string, unknown>;
          const briefing = buildExecutiveBriefing(ctx);
          setFetchedSummary(briefing);
        }
      })
      .catch(() => {
        setFetchedSummary('Unable to load context summary. The strategic context service may not be available.');
      })
      .finally(() => {
        setSummaryLoading(false);
      });
  }, [isOpen, problemSetId, currentSummary]);

  // Reset title when modal opens
  useEffect(() => {
    if (isOpen) {
      setSnapshotTitle(defaultSnapshotTitle());
      setSaveSuccess(false);
      setSaveError(null);
    }
  }, [isOpen]);

  // Keyboard handling: Escape to close, focus trap
  const handleKeyDown = useCallback(
    (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    },
    [onClose],
  );

  useEffect(() => {
    if (isOpen) {
      document.addEventListener('keydown', handleKeyDown);
      // Focus the modal for accessibility
      modalRef.current?.focus();
    }
    return () => {
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [isOpen, handleKeyDown]);

  // ── Save handler ────────────────────────────────────────────────────────────

  const handleSave = useCallback(async () => {
    const summary = currentSummary ?? fetchedSummary ?? '';
    if (!summary) {
      setSaveError('No context summary to save.');
      return;
    }

    setSaving(true);
    setSaveError(null);
    setSaveSuccess(false);

    try {
      await saveSnapshot({
        title: snapshotTitle.trim() || defaultSnapshotTitle(),
        summary,
        timeScale: currentTimeScale,
        nodeCount,
        edgeCount,
      });
      setSaveSuccess(true);
      // Reset after 3s
      setTimeout(() => setSaveSuccess(false), 3000);
    } catch (err) {
      setSaveError(err instanceof Error ? err.message : 'Failed to save snapshot.');
    } finally {
      setSaving(false);
    }
  }, [currentSummary, fetchedSummary, snapshotTitle, currentTimeScale, nodeCount, edgeCount, saveSnapshot]);

  // ── Delete handler ──────────────────────────────────────────────────────────

  const handleDelete = useCallback(
    async (id: string) => {
      setDeletingId(id);
      try {
        await deleteSnapshot(id);
        if (expandedSnapshotId === id) setExpandedSnapshotId(null);
      } finally {
        setDeletingId(null);
      }
    },
    [deleteSnapshot, expandedSnapshotId],
  );

  if (!isOpen) return null;

  const displaySummary = currentSummary ?? fetchedSummary;

  return (
    <div
      className="snapshot-modal-overlay"
      role="dialog"
      aria-modal="true"
      aria-label="Strategic Environment Snapshot"
      onClick={(e) => {
        // Close when clicking the backdrop
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div
        className="snapshot-modal"
        ref={modalRef}
        tabIndex={-1}
      >
        {/* ── Header ────────────────────────────────────────────────────────── */}
        <div className="snapshot-modal-header">
          <span className="snapshot-modal-title">Strategic Environment Snapshot</span>
          <button
            className="snapshot-modal-close"
            onClick={onClose}
            aria-label="Close"
          >
            &times;
          </button>
        </div>

        {/* ── Body ──────────────────────────────────────────────────────────── */}
        <div className="snapshot-modal-body">

          {/* Current context summary */}
          <div className="snapshot-section-label">Executive Briefing</div>
          <div className="snapshot-summary snapshot-briefing" style={{ whiteSpace: 'pre-wrap' }}>
            {summaryLoading
              ? 'Generating briefing...'
              : displaySummary ?? 'No context available.'}
          </div>

          {/* Stats bar */}
          <div className="snapshot-stats">
            <span>{nodeCount} entities</span>
            <span>{edgeCount} connections</span>
            <span>Time scale: {formatTimeScale(currentTimeScale)}</span>
          </div>

          {/* Save section */}
          <div className="snapshot-save-section">
            <div className="snapshot-section-label">Save as Snapshot</div>
            <input
              className="snapshot-title-input"
              type="text"
              value={snapshotTitle}
              onChange={(e) => setSnapshotTitle(e.target.value)}
              placeholder="Snapshot title..."
              aria-label="Snapshot title"
            />
            <button
              className="snapshot-save-btn"
              onClick={handleSave}
              disabled={saving || summaryLoading}
            >
              {saving ? 'Saving...' : 'Save Snapshot'}
            </button>
            {saveSuccess && (
              <div className="snapshot-save-feedback snapshot-save-success">
                Snapshot saved successfully.
              </div>
            )}
            {saveError && (
              <div className="snapshot-save-feedback snapshot-save-error">
                {saveError}
              </div>
            )}
          </div>

          {/* Saved snapshots list */}
          <div className="snapshot-list">
            <div className="snapshot-section-label">
              Saved Snapshots
              {snapshotsLoading && <span className="snapshot-list-loading"> Loading...</span>}
            </div>

            {snapshots.length === 0 && !snapshotsLoading && (
              <div className="snapshot-list-empty">
                No saved snapshots yet. Save a snapshot to create a historical reference.
              </div>
            )}

            {snapshots.map((snapshot: BrainSnapshot) => (
              <div key={snapshot.id} className="snapshot-list-item">
                <div className="snapshot-list-item-header">
                  <div className="snapshot-list-item-info">
                    <span className="snapshot-list-item-title">{snapshot.title}</span>
                    <span className="snapshot-list-item-meta">
                      {formatDate(snapshot.createdAt)} &middot; {snapshot.createdBy} &middot; {snapshot.nodeCount} entities / {snapshot.edgeCount} connections
                    </span>
                  </div>
                  <div className="snapshot-list-item-actions">
                    <button
                      className="snapshot-action-btn"
                      onClick={() =>
                        setExpandedSnapshotId(
                          expandedSnapshotId === snapshot.id ? null : snapshot.id,
                        )
                      }
                      aria-label={expandedSnapshotId === snapshot.id ? 'Collapse' : 'View'}
                    >
                      {expandedSnapshotId === snapshot.id ? 'Hide' : 'View'}
                    </button>
                    <button
                      className="snapshot-action-btn snapshot-delete-btn"
                      onClick={() => handleDelete(snapshot.id)}
                      disabled={deletingId === snapshot.id}
                      aria-label="Delete snapshot"
                    >
                      {deletingId === snapshot.id ? '...' : 'Delete'}
                    </button>
                  </div>
                </div>

                {expandedSnapshotId === snapshot.id && (
                  <div className="snapshot-list-item-body">
                    {snapshot.summary}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
