/**
 * AIContextSnapshotModal
 *
 * Modal overlay showing the AI context summary for the strategic environment
 * at the brain's current time scale. Users can save a snapshot for historical
 * reference and view/delete previously saved snapshots.
 *
 * Saved snapshots are injected into StrategicContextService.assembleContext()
 * making them available as "source of truth" to all BASTION AI agents.
 */

import React, { useState, useEffect, useCallback, useRef } from 'react';
import './AIContextSnapshotModal.css';
import { useBrainSnapshots } from './hooks/useBrainSnapshots.js';
import type { BrainSnapshot } from './hooks/useBrainSnapshots.js';

const BACKEND_URL = import.meta.env.VITE_API_URL ?? '';

// ─── Types ────────────────────────────────────────────────────────────────────

interface AIContextSnapshotModalProps {
  isOpen: boolean;
  onClose: () => void;
  problemSetId: string;
  /** Precomputed AI context summary — generated by the strategic context service */
  currentSummary?: string;
  nodeCount: number;
  edgeCount: number;
  currentTimeScale?: Date;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function formatDate(isoString: string): string {
  const d = new Date(isoString);
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

function formatTimeScale(date?: Date): string {
  if (!date) return 'Current';
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit' });
}

function defaultSnapshotTitle(): string {
  const now = new Date();
  return `Snapshot - ${now.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`;
}

// ─── Component ────────────────────────────────────────────────────────────────

export function AIContextSnapshotModal({
  isOpen,
  onClose,
  problemSetId,
  currentSummary,
  nodeCount,
  edgeCount,
  currentTimeScale,
}: AIContextSnapshotModalProps): React.ReactElement | null {
  const { snapshots, loading: snapshotsLoading, saveSnapshot, deleteSnapshot } = useBrainSnapshots(problemSetId);

  const [fetchedSummary, setFetchedSummary] = useState<string | null>(null);
  const [summaryLoading, setSummaryLoading] = useState(false);

  const [snapshotTitle, setSnapshotTitle] = useState(defaultSnapshotTitle);
  const [saving, setSaving] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);

  const [expandedSnapshotId, setExpandedSnapshotId] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);

  const modalRef = useRef<HTMLDivElement>(null);

  // Fetch context summary if not provided as prop
  useEffect(() => {
    if (!isOpen || currentSummary) return;

    setSummaryLoading(true);
    fetch(`${BACKEND_URL}/api/strategic-context/preview/${encodeURIComponent(problemSetId)}`)
      .then((res) => {
        if (!res.ok) throw new Error(`Failed to load context: ${res.status}`);
        return res.json() as Promise<{ context?: Record<string, unknown> | string | null }>;
      })
      .then((data) => {
        if (!data.context) {
          setFetchedSummary('No context available — add strategic documents or subscribe to a parent problem set.');
        } else if (typeof data.context === 'string') {
          setFetchedSummary(data.context);
        } else {
          // Build a concise narrative from the structured context
          const ctx = data.context as Record<string, unknown>;
          const narrativeParts: string[] = [];

          // Extract graph summaries (contain actual strategic analysis)
          const graphs = ctx.graphSummaries as Record<string, { summary?: string; topActors?: Array<{ name: string; category?: string }>; activeTensions?: Array<{ description: string; intensity?: string }> }> | undefined;
          if (graphs) {
            for (const [, gs] of Object.entries(graphs)) {
              if (gs.summary) narrativeParts.push(gs.summary);
              if (gs.topActors && gs.topActors.length > 0) {
                const actorList = gs.topActors.slice(0, 5).map(a => `${a.name}${a.category ? ` (${a.category})` : ''}`).join(', ');
                narrativeParts.push(`Key actors: ${actorList}.`);
              }
              if (gs.activeTensions && gs.activeTensions.length > 0) {
                const tensionList = gs.activeTensions.slice(0, 3).map(t => `${t.description}${t.intensity ? ` [${t.intensity}]` : ''}`).join('; ');
                narrativeParts.push(`Active tensions: ${tensionList}.`);
              }
            }
          }

          // Extract document summaries
          const docs = ctx.documentSummaries as Array<{ title?: string; extractedData?: { summary?: string }; textContent?: string }> | undefined;
          if (Array.isArray(docs) && docs.length > 0) {
            const docNames = docs.slice(0, 5).map(d => d.title || 'Untitled').join(', ');
            narrativeParts.push(`Based on ${docs.length} strategic document(s): ${docNames}.`);
            // Include first document summary if available
            for (const doc of docs.slice(0, 2)) {
              const docSummary = doc.extractedData?.summary || doc.textContent;
              if (docSummary) {
                narrativeParts.push(docSummary.length > 200 ? docSummary.slice(0, 200) + '...' : docSummary);
              }
            }
          }

          if (narrativeParts.length > 0) {
            setFetchedSummary(narrativeParts.join('\n\n'));
          } else {
            setFetchedSummary('Strategic context data is available but contains no narrative summaries yet. Run graph analysis to generate insights.');
          }
        }
      })
      .catch(() => {
        setFetchedSummary('Unable to load context summary. The strategic context service may not be available.');
      })
      .finally(() => {
        setSummaryLoading(false);
      });
  }, [isOpen, problemSetId, currentSummary]);

  // Reset title when modal opens
  useEffect(() => {
    if (isOpen) {
      setSnapshotTitle(defaultSnapshotTitle());
      setSaveSuccess(false);
      setSaveError(null);
    }
  }, [isOpen]);

  // Keyboard handling: Escape to close, focus trap
  const handleKeyDown = useCallback(
    (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    },
    [onClose],
  );

  useEffect(() => {
    if (isOpen) {
      document.addEventListener('keydown', handleKeyDown);
      // Focus the modal for accessibility
      modalRef.current?.focus();
    }
    return () => {
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [isOpen, handleKeyDown]);

  // ── Save handler ────────────────────────────────────────────────────────────

  const handleSave = useCallback(async () => {
    const summary = currentSummary ?? fetchedSummary ?? '';
    if (!summary) {
      setSaveError('No context summary to save.');
      return;
    }

    setSaving(true);
    setSaveError(null);
    setSaveSuccess(false);

    try {
      await saveSnapshot({
        title: snapshotTitle.trim() || defaultSnapshotTitle(),
        summary,
        timeScale: currentTimeScale,
        nodeCount,
        edgeCount,
      });
      setSaveSuccess(true);
      // Reset after 3s
      setTimeout(() => setSaveSuccess(false), 3000);
    } catch (err) {
      setSaveError(err instanceof Error ? err.message : 'Failed to save snapshot.');
    } finally {
      setSaving(false);
    }
  }, [currentSummary, fetchedSummary, snapshotTitle, currentTimeScale, nodeCount, edgeCount, saveSnapshot]);

  // ── Delete handler ──────────────────────────────────────────────────────────

  const handleDelete = useCallback(
    async (id: string) => {
      setDeletingId(id);
      try {
        await deleteSnapshot(id);
        if (expandedSnapshotId === id) setExpandedSnapshotId(null);
      } finally {
        setDeletingId(null);
      }
    },
    [deleteSnapshot, expandedSnapshotId],
  );

  if (!isOpen) return null;

  const displaySummary = currentSummary ?? fetchedSummary;

  return (
    <div
      className="snapshot-modal-overlay"
      role="dialog"
      aria-modal="true"
      aria-label="Strategic Environment Snapshot"
      onClick={(e) => {
        // Close when clicking the backdrop
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div
        className="snapshot-modal"
        ref={modalRef}
        tabIndex={-1}
      >
        {/* ── Header ────────────────────────────────────────────────────────── */}
        <div className="snapshot-modal-header">
          <span className="snapshot-modal-title">Strategic Environment Snapshot</span>
          <button
            className="snapshot-modal-close"
            onClick={onClose}
            aria-label="Close"
          >
            &times;
          </button>
        </div>

        {/* ── Body ──────────────────────────────────────────────────────────── */}
        <div className="snapshot-modal-body">

          {/* Current context summary */}
          <div className="snapshot-section-label">Current AI Context Summary</div>
          <div className="snapshot-summary" style={{ whiteSpace: 'pre-wrap' }}>
            {summaryLoading
              ? 'Loading context...'
              : displaySummary ?? 'No context available.'}
          </div>

          {/* Stats bar */}
          <div className="snapshot-stats">
            <span>{nodeCount} entities</span>
            <span>{edgeCount} connections</span>
            <span>Time scale: {formatTimeScale(currentTimeScale)}</span>
          </div>

          {/* Save section */}
          <div className="snapshot-save-section">
            <div className="snapshot-section-label">Save as Snapshot</div>
            <input
              className="snapshot-title-input"
              type="text"
              value={snapshotTitle}
              onChange={(e) => setSnapshotTitle(e.target.value)}
              placeholder="Snapshot title..."
              aria-label="Snapshot title"
            />
            <button
              className="snapshot-save-btn"
              onClick={handleSave}
              disabled={saving || summaryLoading}
            >
              {saving ? 'Saving...' : 'Save Snapshot'}
            </button>
            {saveSuccess && (
              <div className="snapshot-save-feedback snapshot-save-success">
                Snapshot saved successfully.
              </div>
            )}
            {saveError && (
              <div className="snapshot-save-feedback snapshot-save-error">
                {saveError}
              </div>
            )}
          </div>

          {/* Saved snapshots list */}
          <div className="snapshot-list">
            <div className="snapshot-section-label">
              Saved Snapshots
              {snapshotsLoading && <span className="snapshot-list-loading"> Loading...</span>}
            </div>

            {snapshots.length === 0 && !snapshotsLoading && (
              <div className="snapshot-list-empty">
                No saved snapshots yet. Save a snapshot to create a historical reference.
              </div>
            )}

            {snapshots.map((snapshot: BrainSnapshot) => (
              <div key={snapshot.id} className="snapshot-list-item">
                <div className="snapshot-list-item-header">
                  <div className="snapshot-list-item-info">
                    <span className="snapshot-list-item-title">{snapshot.title}</span>
                    <span className="snapshot-list-item-meta">
                      {formatDate(snapshot.createdAt)} &middot; {snapshot.createdBy} &middot; {snapshot.nodeCount} entities / {snapshot.edgeCount} connections
                    </span>
                  </div>
                  <div className="snapshot-list-item-actions">
                    <button
                      className="snapshot-action-btn"
                      onClick={() =>
                        setExpandedSnapshotId(
                          expandedSnapshotId === snapshot.id ? null : snapshot.id,
                        )
                      }
                      aria-label={expandedSnapshotId === snapshot.id ? 'Collapse' : 'View'}
                    >
                      {expandedSnapshotId === snapshot.id ? 'Hide' : 'View'}
                    </button>
                    <button
                      className="snapshot-action-btn snapshot-delete-btn"
                      onClick={() => handleDelete(snapshot.id)}
                      disabled={deletingId === snapshot.id}
                      aria-label="Delete snapshot"
                    >
                      {deletingId === snapshot.id ? '...' : 'Delete'}
                    </button>
                  </div>
                </div>

                {expandedSnapshotId === snapshot.id && (
                  <div className="snapshot-list-item-body">
                    {snapshot.summary}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
